/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "build_time:20250121114009 commit:796cae7"
#endif /* AVUTIL_FFVERSION_H */
