
#ifndef _MENU_COMMON_H_
#define _MENU_COMMON_H_

/*===========================================================================
 * Include file 
 *===========================================================================*/ 
#include <cstddef>
#include <cstdio>
#include <stdlib.h>
#include <stdarg.h>
#include "MenuConfig_SDK.h"

/*===========================================================================
 * Macro define 
 *===========================================================================*/ 
#define MAGIC_NUM      (0x123456) //menu setting header
#define HDRTAIL_NUM         (0x0A524448)
#define NUMBER_SETTING		(100)
#define NUMBER_ITEM_VALS    (35)

struct _setting_atom;
typedef int (*MFUN)(struct _setting_atom*, int, char*, void*);
typedef int (*GET_FUN)(int icur_val, va_list *ap);

typedef struct sMENU*  PSMENUSTRUCT;
typedef struct sITEM*  PSMENUITEM;

typedef  bool	(*pfItemHandler)(PSMENUITEM pItem );
typedef  int 	(*pfMenuEventHandler)(PSMENUSTRUCT pMenu, int ulEvent, int ulParam );
typedef  int 	(*pfMenuGetDefault)(PSMENUSTRUCT pMenu );

/*===========================================================================
 * Structure define 
 *===========================================================================*/
typedef struct _settingtovals {
    const char*   szItemKey;
    int       nItemValue;
} SETTING_VALS;

typedef struct _setting_atom {
    const char*       szSKey;
    int         nSVal;
    int         bSAct;
    MFUN     fnSet;
    GET_FUN     fnGet;
    SETTING_VALS  szItemMaps[NUMBER_ITEM_VALS];
} SETTING_ATOM;

typedef struct {
    int             HDR_MAGIC;
    int             HDR_TAIL;
    SETTING_ATOM    sAtom[NUMBER_SETTING];
} MENU_ATOMS;

typedef struct sITEM {
    int iItemId;
    int iStringId;
    struct sMENU* pSubMenu;
    pfItemHandler pfItemSelectHandler;
} SMENUITEM, *PSMENUITEM;

typedef struct sMENU {
    int iMenuId;
    int iStringId;
    struct sMENU* pParentMenu;
    int iNumOfItems;
    PSMENUITEM* pItemsList;
    pfMenuGetDefault pfMenuGetDefaultVal;
    int iCurrentPos;
} SMENUSTRUCT, *PSMENUSTRUCT;

typedef struct _MenuInfo
{
// Still
    int uiIMGSize;            // 0
    int uiIMGQuality;
    int uiBurstShot;
// Movie
    int uiMOVSize;
    int uiMOVQuality;
    int uiMicSensitivity;
    int uiMOVPreRecord;
    int uiMOVClipTime;
    int uiMOVPowerOffTime;    // 8
    int uiMOVSoundRecord;
    int uiMOVRecordVolume;
    int uiVMDRecTime;
    int uiAutoRec;
    int uiTimeLapseTime;      // 12
    int uiSlowMotion;
    int uiHDR;
    int uiWNR;
    int uiNightMode;
    int uiParkingMode;
    int uiLDWS;
    int uiFCWS;
    int uiSAG;
    int uiContrast;
    int uiSaturation;
    int uiSharpness;
    int uiGamma;
// Manual
    int uiScene ;
    int uiEV;
    int uiISO;
    int uiWB;
    int uiColor;
    int uiEffect;             // 30
// Playback
    int uiPlaybackVideoType;
    int uiSlideShowStart;
    int uiSlideShowFile;      // 33
    int uiSlideShowEffect;
    int uiSlideShowMusic;
    int uiVolume;
// Edit Tool
    int uiFileEdit;
// Media Tool
    int uiMediaSelect;        // 38
// General
    int uiBeep;
    int uiLCDBrightness;
    int uiAutoPowerOff;
    int uiDateTimeFormat;
    int uiDateLogoStamp;
    int uiGPSStamp;
    int uiSpeedStamp;
    int uiLanguage;
    int uiResetSetting;
    int uiFlickerHz;
    int uiUSBFunction;
    int uiLCDPowerSave;
    int uiGsensorSensitivity;
    int uiPowerOnGsensorSensitivity;
    int uiTimeZone;
    int uiMotionDtcSensitivity;
// Battery
    int uiBatteryVoltage;
//Wifi
    int uiWifi;
//version
    int uiVersion;      //56
} MenuInfo, *pMenuInfo;

/*===========================================================================
 * Enum define 
 *===========================================================================*/ 
//Menu Item
typedef enum{
    MENUID_MAIN_MENU_VIDEO          ,
    MENUID_MAIN_MENU_STILL          ,
    MENUID_MAIN_MENU_PLAYBACK       ,
    MENUID_MAIN_MENU_EDIT           ,
    MENUID_MAIN_MENU_MEDIA          ,
    MENUID_MAIN_MENU_GENERAL        ,
    MENUID_MAIN_MAX
}MENUID_MAIN;

 typedef enum{
    MENUID_SUB_MENU_MOVIE_MODE = 0          , // 0
    MENUID_SUB_MENU_MOVIE_QUALITY        	,
    MENUID_SUB_MENU_MIC_SENSITIVITY      	,
    MENUID_SUB_MENU_MOVIE_PRERECORD		 	,
    MENUID_SUB_MENU_MOVIE_POWER_OFF_TIME 	,

    MENUID_SUB_MENU_MOVIE_VMD_REC_TIME 		, // 5
    MENUID_SUB_MENU_MOVIE_SOUND_RECORD   	,
    MENUID_SUB_MENU_MOVIE_RECORD_VOLUME     ,
    MENUID_SUB_MENU_MOVIE_CLIPTIME       	,
    MENUID_SUB_MENU_MOVIE_NIGHT_MODE        ,
    MENUID_SUB_MENU_MOVIE_AUTO_REC			,

    MENUID_SUB_MENU_MOVIE_TIMELAPSE         , // 10
    MENUID_SUB_MENU_MOVIE_PARKING_MODE      ,
    MENUID_SUB_MENU_MOVIE_LDWS_MODE         ,
    MENUID_SUB_MENU_MOVIE_FCWS_MODE         ,
    MENUID_SUB_MENU_MOVIE_SAG_MODE          ,

    MENUID_SUB_MENU_MOVIE_HDR_MODE          , // 15
    MENUID_SUB_MENU_MOVIE_SLOWMOTION_MODE   ,
    MENUID_SUB_MENU_MOVIE_WNR_MODE          ,
    MENUID_SUB_MENU_STILL_IMAGE_SIZE     	,
    MENUID_SUB_MENU_STILL_QUALITY        	,

    MENUID_SUB_MENU_BURST_CAPTURE        	, // 20
    MENUID_SUB_MENU_VMD_SHOT_NUM        	,   
    MENUID_SUB_MENU_SCENCE          	    ,
    MENUID_SUB_MENU_EV                   	,
    MENUID_SUB_MENU_ISO                  	,

    MENUID_SUB_MENU_WB                   	, // 25
    MENUID_SUB_MENU_COLOR                	,
    MENUID_SUB_MENU_EFFECT               	,
    MENUID_SUB_MENU_FACE_TOUCH           	,
    MENUID_SUB_MENU_SMILE_DETECTION      	,

    MENUID_SUB_MENU_SMILE_SENSITIVITY    	, // 30
    MENUID_SUB_MENU_CONTRAST                ,
    MENUID_SUB_MENU_SATURATION              ,
    MENUID_SUB_MENU_SHARPNESS               ,
    MENUID_SUB_MENU_GAMMA                   ,

    MENUID_SUB_MENU_ROTATE               	, // 35
    MENUID_SUB_MENU_SLIDE_SHOW_FILES     	,
    MENUID_SUB_MENU_SLIDE_SHOW_EFFECTS   	,
    MENUID_SUB_MENU_SLIDE_SHOW_MUSIC     	,
    MENUID_SUB_MENU_VOLUME               	,

    MENUID_SUB_MENU_VIDEO_TYPE              , // 40
    MENUID_SUB_MENU_VIDEO_CAMID             ,
    MENUID_SUB_MENU_DELETE_FILE             ,
    MENUID_SUB_MENU_DELETE               	,
    MENUID_SUB_MENU_DELETE_ALL           	,

    MENUID_SUB_MENU_DELETE_ALL_VIDEO	 	, // 45
    MENUID_SUB_MENU_DELETE_ALL_IMAGE	 	,
    MENUID_SUB_MENU_DELETE_GLOCK         	,
    MENUID_SUB_MENU_PROTECT_FILE            ,
    MENUID_SUB_MENU_PROTECT              	,

    MENUID_SUB_MENU_PROTECT_ALL          	, // 50
    MENUID_SUB_MENU_PROTECT_ALL_VIDEO	 	,
    MENUID_SUB_MENU_PROTECT_ALL_IMAGE	 	,
    MENUID_SUB_MENU_UNPROTECT_FILE          ,
    MENUID_SUB_MENU_UNPROTECT_ALL	     	,

    MENUID_SUB_MENU_UNPROTECT_ALL_VIDEO	 	, //55
    MENUID_SUB_MENU_UNPROTECT_ALL_IMAGE	 	,
    MENUID_SUB_MENU_MEDIA_SELECT         	,
    MENUID_SUB_MENU_FORMAT_SD_CARD       	,
    MENUID_SUB_MENU_FORMAT_INTMEM        	,

    MENUID_SUB_MENU_SD_CARD_INFO         	, // 60
    MENUID_SUB_MENU_INTMEM_INFO          	,
    MENUID_SUB_MENU_BEEP                 	,
    MENUID_SUB_MENU_LCD_BRIGHTNESS       	,
    MENUID_SUB_MENU_AUTO_POWER_OFF       	,

    MENUID_SUB_MENU_CLOCK_SETTINGS       	, // 65
    MENUID_SUB_MENU_DRIVER_ID_SETTINGS		,
    MENUID_SUB_MENU_DATETIME_FORMAT      	,
    MENUID_SUB_MENU_DATELOGO_STAMP		 	,
    MENUID_SUB_MENU_GPS_STAMP		 		,

    MENUID_SUB_MENU_SPEED_STAMP		 		, // 70
    MENUID_SUB_MENU_LANGUAGE             	,
    MENUID_SUB_MENU_RESET_SETUP          	,
    MENUID_SUB_MENU_FLICKER_FREQUENCY    	,
    MENUID_SUB_MENU_GSENSOR_SENSITIVITY  	,

    MENUID_SUB_MENU_MOTION_DTC_SENSITIVITY  , // 75
    MENUID_SUB_MENU_GPS_INFO             	,
    MENUID_SUB_MENU_LCD_ROTATE		     	,
    MENUID_SUB_MENU_USB_FUNCTION	     	,
    MENUID_SUB_MENU_LCD_POWER_SAVE	     	,

    MENUID_SUB_MENU_TIME_ZONE		     	, // 80
    MENUID_SUB_MENU_NIGHT_MODE				,
    MENUID_SUB_MENU_FW_VERSION_INFO			,
    MENUID_SUB_MENU_GSENSOR_POWERON_SENSITIVITY,
    MENUID_SUB_MENU_WIFI_MODE               ,

    MENUID_SUB_MENU_PQ_CONTRAST             , // 85
    MENUID_SUB_MENU_PQ_BRIGHTNESS           ,
    MENUID_SUB_MENU_PQ_SATURATION           ,
    MENUID_SUB_MENU_PQ_COLORTEMP            ,

#if (MENU_WIFI_PAGE_EN)
    MENUID_SUB_MENU_WIFI_MODE_1,
    MENUID_SUB_MENU_WIFI_AP,
    MENUID_SUB_MENU_WIFI_AP_SSID,
    MENUID_SUB_MENU_WIFI_AP_PSWD,
    MENUID_SUB_MENU_WIFI_STATION,

    MENUID_SUB_MENU_WIFI_STATION1_SSID,
    MENUID_SUB_MENU_WIFI_STATION1_PSWD,
    MENUID_SUB_MENU_WIFI_STATION2_SSID,
    MENUID_SUB_MENU_WIFI_STATION2_PSWD,
    MENUID_SUB_MENU_WIFI_STATION3_SSID,

    MENUID_SUB_MENU_WIFI_STATION3_PSWD,
    MENUID_SUB_MENU_WIFI_STATION4_SSID,
    MENUID_SUB_MENU_WIFI_STATION4_PSWD,
    MENUID_SUB_MENU_WIFI_STATION5_SSID,
    MENUID_SUB_MENU_WIFI_STATION5_PSWD,

    MENUID_SUB_MENU_WIFI_STATION6_SSID,
    MENUID_SUB_MENU_WIFI_STATION6_PSWD,
#endif
#if (MENU_REARCAM_TYPE_EN)
    MENUID_SUB_MENU_REAR_TYPE,
#endif

#if (MENU_GENERAL_SYSTEM_SETTINGS_EN)
    MENUID_SUB_MENU_SYSTEM_SETTINGS,
#endif
    MENUID_SUB_MENU_MAX
}MENUID_SUB;
typedef enum {

#if MENU_MOVIE_SIZE_EN
    ITEMID_MOVIE_MODE= 0,
#if (MENU_MOVIE_SIZE_4K_25P_EN)
    ITEMID_MOVIE_MODE_4K_25P,
#endif
#if (MENU_MOVIE_SIZE_1440_30P_EN)
    ITEMID_MOVIE_MODE_1440_30P,
#endif
#if (MENU_MOVIE_SIZE_SHD_30P_EN)
    ITEMID_MOVIE_MODE_SHD,
#endif
#if (MENU_MOVIE_SIZE_SHD_25P_EN)
    ITEMID_MOVIE_MODE_SHD_25P,
#endif
#if (MENU_MOVIE_SIZE_1080_60P_EN)
    ITEMID_MOVIE_MODE_FHD_60P,
#endif
#if (MENU_MOVIE_SIZE_1080P_30_HDR_EN)
    ITEMID_MOVIE_MODE_FHD_HDR,
#endif
#if (MENU_MOVIE_SIZE_1080P_EN)
    ITEMID_MOVIE_MODE_FHD,
#endif
#if (MENU_MOVIE_SIZE_720P_EN)
    ITEMID_MOVIE_MODE_HD,
#endif
#if (MENU_MOVIE_SIZE_720_60P_EN)
    ITEMID_MOVIE_MODE_HD_60P,
#endif
#if (MENU_MOVIE_SIZE_VGA30P_EN)
    ITEMID_MOVIE_MODE_VGA_30P,
#endif
#endif

#if MENU_MOVIE_QUALITY_EN
    ITEMID_MOVIE_QUALITY,
#if (MENU_MOVIE_QUALITY_SUPER_FINE_EN)
    ITEMID_MQUALITY_SUPERFINE,
#endif
#if (MENU_MOVIE_QUALITY_FINE_EN)
    ITEMID_MQUALITY_FINE,
#endif
#endif

#if MENU_MOVIE_MIC_SEN_EN
    ITEMID_MIC_SENSITIVITY,
#if (MENU_MOVIE_MIC_SEN_STANDARD_EN)
    ITEMID_MIC_SENSITI_STANDARD,
#endif
#if (MENU_MOVIE_MIC_SEN_LOW_EN)
    ITEMID_MIC_SENSITI_LOW,
#endif
#endif

#if MENU_MOVIE_PRE_RECORD_EN
    ITEMID_MOVIE_PRE_RECORD,
    ITEMID_MOVIE_PRE_RECORD_ON,
    ITEMID_MOVIE_PRE_RECORD_OFF,
#endif

#if MENU_MOVIE_SOUND_RECORD_EN
    ITEMID_MOVIE_SOUND_RECORD,
    ITEMID_MOVIE_SOUND_RECORD_ON,
    ITEMID_MOVIE_SOUND_RECORD_OFF,
#endif

#if MENU_MOVIE_RECORD_VOLUME_EN
    ITEMID_MOVIE_RECORD_VOLUME,
    ITEMID_MOVIE_RECORD_VOLUME_INC,
    ITEMID_MOVIE_RECORD_VOLUME_DEC,
#endif

#if MENU_MOVIE_CLIP_TIME_EN
    ITEMID_MOVIE_CLIPTIME,
#if (MENU_MOVIE_CLIP_TIME_OFF_EN)
    ITEMID_MOVIE_CLIPTIME_OFF,
#endif
#if (MENU_MOVIE_CLIP_TIME_1MIN_EN)
    ITEMID_MOVIE_CLIPTIME_1MIN,
#endif
#if (MENU_MOVIE_CLIP_TIME_2MIN_EN)
    ITEMID_MOVIE_CLIPTIME_2MIN,
#endif
#if (MENU_MOVIE_CLIP_TIME_3MIN_EN)
    ITEMID_MOVIE_CLIPTIME_3MIN,
#endif
#if (MENU_MOVIE_CLIP_TIME_5MIN_EN)
    ITEMID_MOVIE_CLIPTIME_5MIN,
#endif
#if (MENU_MOVIE_CLIP_TIME_10MIN_EN)
    ITEMID_MOVIE_CLIPTIME_10MIN,
#endif
#if (MENU_MOVIE_CLIP_TIME_30MIN_EN)
    ITEMID_MOVIE_CLIPTIME_30MIN,
#endif
#endif

#if MENU_MOVIE_NIGHT_MODE_EN
    ITEMID_MOVIE_NIGHT_MODE,
    ITEMID_MOVIE_NIGHT_MODE_ON,
    ITEMID_MOVIE_NIGHT_MODE_OFF,
#endif

#if MENU_MOVIE_POWER_OFF_DELAY_EN
    ITEMID_MOVIE_POWEROFF_TIME,
#if (MENU_MOVIE_POWER_OFF_DELAY_0SEC_EN)
    ITEMID_MOVIE_POWEROFF_TIME_0MIN,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_5SEC_EN)
    ITEMID_MOVIE_POWEROFF_TIME_5SEC,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_10SEC_EN)
    ITEMID_MOVIE_POWEROFF_TIME_10SEC,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_15SEC_EN)
    ITEMID_MOVIE_POWEROFF_TIME_15SEC,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_30SEC_EN)
    ITEMID_MOVIE_POWEROFF_TIME_30SEC,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_1MIN_EN)
    ITEMID_MOVIE_POWEROFF_TIME_1MIN,
#endif
#endif

#if MENU_MOVIE_VMD_REC_TIME_EN
    ITEMID_MOVIE_VMD_REC_TIME,
#if (MENU_MOVIE_VMD_REC_TIME_5SEC_EN)
    ITEMID_MOVIE_VMD_REC_TIME_5SEC,
#endif
#if (MENU_MOVIE_VMD_REC_TIME_10SEC_EN)
    ITEMID_MOVIE_VMD_REC_TIME_10SEC,
#endif
#if (MENU_MOVIE_VMD_REC_TIME_30SEC_EN)
    ITEMID_MOVIE_VMD_REC_TIME_30SEC,
#endif
#if (MENU_MOVIE_VMD_REC_TIME_1MIN_EN)
    ITEMID_MOVIE_VMD_REC_TIME_1MIN,
#endif
#endif

#if  MENU_MOVIE_AUTO_REC_EN
    ITEMID_MOVIE_AUTO_REC,
    ITEMID_MOVIE_AUTO_REC_ON,
    ITEMID_MOVIE_AUTO_REC_OFF,
#endif

#if (MENU_MOVIE_TIMELAPSE_MODE_EN)
    ITEMID_MOVIE_TIMELAPSE,
#if (MENU_VIDEO_TIMELAPSE_MODE_OFF_EN)
    ITEMID_MOVIE_TIMELAPSE_OFF,
#endif
#if (MENU_VIDEO_TIMELAPSE_MODE_1SEC_EN)
    ITEMID_MOVIE_TIMELAPSE_1SEC,
#endif
#if (MENU_VIDEO_TIMELAPSE_MODE_5SEC_EN)
    ITEMID_MOVIE_TIMELAPSE_5SEC,
#endif
#if (MENU_VIDEO_TIMELAPSE_MODE_10SEC_EN)
    ITEMID_MOVIE_TIMELAPSE_10SEC,
#endif
#if (MENU_VIDEO_TIMELAPSE_MODE_30SEC_EN)
    ITEMID_MOVIE_TIMELAPSE_30SEC,
#endif
#if (MENU_VIDEO_TIMELAPSE_MODE_60SEC_EN)
    ITEMID_MOVIE_TIMELAPSE_60SEC,
#endif
#endif

#if (MENU_MOVIE_PARKING_MODE_EN)
    ITEMID_MOVIE_PARKING_MODE,
    ITEMID_MOVIE_PARKING_MODE_ON,
    ITEMID_MOVIE_PARKING_MODE_OFF,
#endif

#if (MENU_MOVIE_LDWS_MODE_EN)
    ITEMID_MOVIE_LDWS_MODE,
    ITEMID_MOVIE_LDWS_MODE_ON,
    ITEMID_MOVIE_LDWS_MODE_OFF,
#endif

#if (MENU_MOVIE_FCWS_MODE_EN)
    ITEMID_MOVIE_FCWS_MODE,
    ITEMID_MOVIE_FCWS_MODE_ON,
    ITEMID_MOVIE_FCWS_MODE_OFF,
#endif

#if (MENU_MOVIE_SAG_MODE_EN)
    ITEMID_MOVIE_SAG_MODE,
    ITEMID_MOVIE_SAG_MODE_ON,
    ITEMID_MOVIE_SAG_MODE_OFF,
#endif

#if (MENU_MOVIE_HDR_MODE_EN)
    ITEMID_MOVIE_HDR_MODE,
    ITEMID_MOVIE_HDR_MODE_ON,
    ITEMID_MOVIE_HDR_MODE_OFF,
#endif

#if (MENU_MOVIE_SLOWMOTION_MODE_EN)
    ITEMID_MOVIE_SLOWMOTION_MODE,
    ITEMID_MOVIE_SLOWMOTION_MODE_X1,
    ITEMID_MOVIE_SLOWMOTION_MODE_X2,
    ITEMID_MOVIE_SLOWMOTION_MODE_X4,
    ITEMID_MOVIE_SLOWMOTION_MODE_X8,
#endif

#if (MENU_MOVIE_WNR_MODE_EN)
    ITEMID_MOVIE_WNR_MODE,
    ITEMID_MOVIE_WNR_MODE_OFF,
    ITEMID_MOVIE_WNR_MODE_ON,
#endif
    ITEMID_MOVIE_ITEM_END
}MOVIEITEMID;

typedef enum {

#if 1//MENU_STILL_SIZE_EN
    ITEMID_STILL_IMAGE_SIZE = ITEMID_MOVIE_ITEM_END,
#if (MENU_STILL_SIZE_30M_EN)    
    ITEMID_IMAGE_SIZE_30M,
#endif
#if (MENU_STILL_SIZE_14M_EN)    
    ITEMID_IMAGE_SIZE_14M,
#endif
#if (MENU_STILL_SIZE_12M_EN)    
    ITEMID_IMAGE_SIZE_12M,
#endif
#if (MENU_STILL_SIZE_8M_EN)    
    ITEMID_IMAGE_SIZE_8M,
#endif
#if (MENU_STILL_SIZE_5M_EN)        
    ITEMID_IMAGE_SIZE_5M,
#endif
#if (MENU_STILL_SIZE_3M_EN)    
    ITEMID_IMAGE_SIZE_3M,
#endif
#if (MENU_STILL_SIZE_2M_WIDE_EN)    
    ITEMID_IMAGE_SIZE_2M,
#endif
#if (MENU_STILL_SIZE_1d2M_EN)    
    ITEMID_IMAGE_SIZE_1_2M,
#endif    
#if (MENU_STILL_SIZE_VGA_EN)
    ITEMID_IMAGE_SIZE_VGA,
#endif
#endif

#if MENU_STILL_QUALITY_EN
    ITEMID_STILL_QUALITY,
#if (MENU_STILL_QUALITY_SUPER_FINE_EN)
    ITEMID_SQUALITY_SUPERFINE,
#endif
#if (MENU_STILL_QUALITY_FINE_EN)    
    ITEMID_SQUALITY_FINE,
#endif  
#endif

    ITEMID_STILL_END    
} CAMERAITEMID;

typedef enum {
    ITEMID_DELETE		 =  ITEMID_STILL_END,
    ITEMID_DELETE_ALL,
    ITEMID_DELETE_ALL_YES,
    ITEMID_DELETE_ALL_NO,
    ITEMID_DELETE_GLOCK,
    ITEMID_DELETE_GLOCK_YES,
    ITEMID_DELETE_GLOCK_NO,
    ITEMID_PROTECT,
    ITEMID_PROTECT_ALL,
    ITEMID_PROTECT_ALL_YES,
    ITEMID_PROTECT_ALL_NO,
    ITEMID_DELETE_ONE,
    ITEMID_DELETE_ONE_YES,
    ITEMID_DELETE_ONE_NO,
    ITEMID_PROTECT_ONE,
    ITEMID_PROTECT_ONE_YES,
    ITEMID_PROTECT_ONE_NO,
    ITEMID_UNPROTECT_ONE,
    ITEMID_UNPROTECT_ONE_YES,
    ITEMID_UNPROTECT_ONE_NO,
    ITEMID_UNPROTECT_ALL,
    ITEMID_UNPROTECT_ALL_YES,
    ITEMID_UNPROTECT_ALL_NO,
    ITEMID_DELETE_ALL_VIDEO,
    ITEMID_DELETE_ALL_VIDEO_YES,
    ITEMID_DELETE_ALL_VIDEO_NO,
    ITEMID_DELETE_ALL_IMAGE,
    ITEMID_DELETE_ALL_IMAGE_YES,
    ITEMID_DELETE_ALL_IMAGE_NO,
    ITEMID_DELETE_ALL_FILE,
    ITEMID_DELETE_ALL_FILE_YES,
    ITEMID_DELETE_ALL_FILE_NO,
    ITEMID_PROTECT_ALL_VIDEO,
    ITEMID_PROTECT_ALL_VIDEO_YES,
    ITEMID_PROTECT_ALL_VIDEO_NO,
    ITEMID_PROTECT_ALL_IMAGE,
    ITEMID_PROTECT_ALL_IMAGE_YES,
    ITEMID_PROTECT_ALL_IMAGE_NO,
    ITEMID_PROTECT_ALL_FILE,
    ITEMID_PROTECT_ALL_FILE_YES,
    ITEMID_PROTECT_ALL_FILE_NO,
    ITEMID_UNPROTECT_ALL_VIDEO,
    ITEMID_UNPROTECT_ALL_VIDEO_YES,
    ITEMID_UNPROTECT_ALL_VIDEO_NO,
    ITEMID_UNPROTECT_ALL_IMAGE,
    ITEMID_UNPROTECT_ALL_IMAGE_YES,
    ITEMID_UNPROTECT_ALL_IMAGE_NO,
    ITEMID_UNPROTECT_ALL_FILE,
    ITEMID_UNPROTECT_ALL_FILE_YES,
    ITEMID_UNPROTECT_ALL_FILE_NO,
    ITEMID_DELETE_FILE,
    ITEMID_DELETE_CANCEL,
    ITEMID_DELETE_FILE_LAST,
    ITEMID_DELETE_FILE_ALL,
    ITEMID_DELETE_VIDEO_ONE,
    ITEMID_DELETE_IMAGE_ONE,
    ITEMID_DELETE_FILE_ONE,
    ITEMID_PROTECT_VIDEO_ONE,
    ITEMID_PROTECT_IMAGE_ONE,
    ITEMID_PROTECT_FILE_ONE,
    ITEMID_UNPROTECT_VIDEO_ONE,
    ITEMID_UNPROTECT_IMAGE_ONE,
    ITEMID_UNPROTECT_FILE_ONE,

    ITEMID_EDITTOOL_END,
		
} EDITTOOLITEMID;

typedef enum {

#if 1//MENU_GENERAL_BEEP_EN
    ITEMID_BEEP     = ITEMID_EDITTOOL_END,
    ITEMID_BEEP_ON,
    ITEMID_BEEP_OFF,
#endif

	ITEMID_LCD_BRI,
	ITEMID_LCD_BRI_DEC,
	ITEMID_LCD_BRI_INC,

#if MENU_GENERAL_AUTO_POWEROFF_EN
    ITEMID_AUTO_POWER_OFF,
#if (MENU_GENERAL_AUTO_POWEROFF_NEVER_EN)
    ITEMID_AUTO_POWER_OFF_NEVER,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_15SEC_EN)
    ITEMID_AUTO_POWER_OFF_15SEC,
#endif

#if (MENU_GENERAL_AUTO_POWEROFF_30SEC_EN)
    ITEMID_AUTO_POWER_OFF_30SEC,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_1MIN_EN)
    ITEMID_AUTO_POWER_OFF_1MIN,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_2MIN_EN)
    ITEMID_AUTO_POWER_OFF_2MIN,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_3MIN_EN)
    ITEMID_AUTO_POWER_OFF_3MIN,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_5MIN_EN)
    ITEMID_AUTO_POWER_OFF_5MIN,
#endif
#endif

    ITEMID_CLOCK_SETTINGS,
    ITEMID_DATETIME_YEAR,
    ITEMID_DATETIME_MONTH,
    ITEMID_DATETIME_DAY,
    ITEMID_DATETIME_HOUR,
    ITEMID_DATETIME_MINUTE,
    ITEMID_DATETIME_SEC,
    ITEMID_DATETIME_OK,
    ITEMID_DATETIME_CANCEL,

#if MENU_GENERAL_DATE_FORMAT_EN
    ITEMID_DATETIME_FORMAT,
#if (MENU_GENERAL_DATE_FORMAT_NONE_EN)
    ITEMID_DATETIME_NONE,
#endif
#if (MENU_GENERAL_DATE_FORMAT_YMD_EN)
    ITEMID_DATETIME_YMD,
#endif
#if (MENU_GENERAL_DATE_FORMAT_MDY_EN)
    ITEMID_DATETIME_MDY,
#endif
#if (MENU_GENERAL_DATE_FORMAT_DMY_EN)
    ITEMID_DATETIME_DMY,
#endif
#endif

#if MENU_GENERAL_LANGUAGE_EN
    ITEMID_LANGUAGE,
#if (MENU_GENERAL_LANGUAGE_ENGLISH_EN)
    ITEMID_LANGUAGES_ENGLISH,
#endif
#if (MENU_GENERAL_LANGUAGE_SPANISH_EN)
    ITEMID_LANGUAGES_SPANISH,
#endif
#if (MENU_GENERAL_LANGUAGE_PORTUGUESE_EN)
    ITEMID_LANGUAGES_PORTUGUESE,
#endif
#if (MENU_GENERAL_LANGUAGE_RUSSIAN_EN)
    ITEMID_LANGUAGES_RUSSIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_SCHINESE_EN)
    ITEMID_LANGUAGES_SCHINESE,
#endif
#if (MENU_GENERAL_LANGUAGE_TCHINESE_EN)
    ITEMID_LANGUAGES_TCHINESE,
#endif
#if (MENU_GENERAL_LANGUAGE_GERMAN_EN)
    ITEMID_LANGUAGES_GERMAN,
#endif
#if (MENU_GENERAL_LANGUAGE_ITALIAN_EN)
    ITEMID_LANGUAGES_ITALIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_LATVIAN_EN)
    ITEMID_LANGUAGES_LATVIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_POLISH_EN)
    ITEMID_LANGUAGES_POLISH,
#endif
#if (MENU_GENERAL_LANGUAGE_ROMANIAN_EN)
    ITEMID_LANGUAGES_ROMANIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_SLOVAK_EN)
    ITEMID_LANGUAGES_SLOVAK,
#endif
#if (MENU_GENERAL_LANGUAGE_UKRANINIAN_EN)
    ITEMID_LANGUAGES_UKRANINIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_FRENCH_EN)
    ITEMID_LANGUAGES_FRENCH,
#endif
#if (MENU_GENERAL_LANGUAGE_JAPANESE_EN)
    ITEMID_LANGUAGES_JAPANESE,
#endif
#if (MENU_GENERAL_LANGUAGE_KOREAN_EN)
    ITEMID_LANGUAGES_KOREAN,
#endif
#if (MENU_GENERAL_LANGUAGE_CZECH_EN)
    ITEMID_LANGUAGES_CZECH,
#endif
#endif

#if MENU_GENERAL_RESET_SETUP_EN
    ITEMID_RESET_SETUP,
    ITEMID_RESET_YES,
    ITEMID_RESET_NO,
#endif

#if MENU_GENERAL_FLICKER_EN
    ITEMID_FLICKER,
    ITEMID_FLICKER_50HZ,
    ITEMID_FLICKER_60HZ,
#endif

    ITEMID_GSENSOR,
    ITEMID_GSENSOR_CLOSE,
    ITEMID_GSENSOR_2G,
    ITEMID_GSENSOR_3G,
    ITEMID_GSENSOR_4G,
    ITEMID_GSENSOR_5G,
    ITEMID_GSENSOR_6G,

    ITEMID_GPS_INFO_CHART,
    ITEMID_GPS_INFO,

    ITEMID_TIME_ZONE,           //0x43
    ITEMID_TIME_ZONE_GMT_M_12,  //01
    ITEMID_TIME_ZONE_GMT_M_11,
    ITEMID_TIME_ZONE_GMT_M_10,
    ITEMID_TIME_ZONE_GMT_M_9,
    ITEMID_TIME_ZONE_GMT_M_8,   //05
    ITEMID_TIME_ZONE_GMT_M_7,
    ITEMID_TIME_ZONE_GMT_M_6,
    ITEMID_TIME_ZONE_GMT_M_5,
    ITEMID_TIME_ZONE_GMT_M_4,
    ITEMID_TIME_ZONE_GMT_M_3_30,//10
    ITEMID_TIME_ZONE_GMT_M_3,
    ITEMID_TIME_ZONE_GMT_M_2,
    ITEMID_TIME_ZONE_GMT_M_1,
    ITEMID_TIME_ZONE_GMT,
    ITEMID_TIME_ZONE_GMT_P_1,   //15
    ITEMID_TIME_ZONE_GMT_P_2,
    ITEMID_TIME_ZONE_GMT_P_3,
    ITEMID_TIME_ZONE_GMT_P_3_30,
    ITEMID_TIME_ZONE_GMT_P_4,
    ITEMID_TIME_ZONE_GMT_P_4_30,//20
    ITEMID_TIME_ZONE_GMT_P_5,
    ITEMID_TIME_ZONE_GMT_P_5_30,
    ITEMID_TIME_ZONE_GMT_P_5_45,
    ITEMID_TIME_ZONE_GMT_P_6,
    ITEMID_TIME_ZONE_GMT_P_6_30,//25
    ITEMID_TIME_ZONE_GMT_P_7,
    ITEMID_TIME_ZONE_GMT_P_8,
    ITEMID_TIME_ZONE_GMT_P_9,
    ITEMID_TIME_ZONE_GMT_P_9_30,
    ITEMID_TIME_ZONE_GMT_P_10,  //30
    ITEMID_TIME_ZONE_GMT_P_11,
    ITEMID_TIME_ZONE_GMT_P_12,
    ITEMID_TIME_ZONE_GMT_P_13,  //33

    ITEMID_FW_VERSION_INFO,
    ITEMID_FW_VERSION,

#if MENU_GENERAL_USB_FUNCTION_EN
    ITEMID_USB_FUNCTION,
#if (MENU_GENERAL_USB_FUNCTION_MSDC_EN)
    ITEMID_USB_MSDC,
#endif
#if (MENU_GENERAL_USB_FUNCTION_PCAM_EN)
    ITEMID_USB_PCAM,
#endif
#endif

#if MENU_GENERAL_LCD_POWER_SAVE_EN
    ITEMID_LCD_POWER_SAVE,
#if (MENU_GENERAL_LCD_POWER_SAVE_OFF_EN)
    ITEMID_LCD_POWER_SAVE_OFF,
#endif
#if (MENU_GENERAL_LCD_POWER_SAVE_10SEC_EN)
    ITEMID_LCD_POWER_SAVE_10SEC,
#endif
#if (MENU_GENERAL_LCD_POWER_SAVE_30SEC_EN)
    ITEMID_LCD_POWER_SAVE_30SEC,
#endif
#if (MENU_GENERAL_LCD_POWER_SAVE_1MIN_EN)
    ITEMID_LCD_POWER_SAVE_1MIN,
#endif
#if (MENU_GENERAL_LCD_POWER_SAVE_3MIN_EN)
    ITEMID_LCD_POWER_SAVE_3MIN,
#endif
#endif

#if (MENU_GENERAL_GSENSOR_OFF_EN)
    ITEMID_GSENSOR_SENSITIVITY,
    ITEMID_GSENSOR_SENSITIVITY_OFF,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL0_EN)
    ITEMID_GSENSOR_SENSITIVITY_L0,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL1_EN)
    ITEMID_GSENSOR_SENSITIVITY_L1,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL2_EN)
    ITEMID_GSENSOR_SENSITIVITY_L2,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL3_EN)
    ITEMID_GSENSOR_SENSITIVITY_L3,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL4_EN)
    ITEMID_GSENSOR_SENSITIVITY_L4,
#endif

#if MENU_GENERAL_DATE_LOGO_STAMP_EN
	ITEMID_DATE_LOGO_STAMP,
#if (MENU_GENERAL_DATE_LOGO_STAMP_DATE_LOGO_EN)
	ITEMID_STAMP_DATELOGO,
#endif
#if (MENU_GENERAL_DATE_LOGO_STAMP_DATE_EN)
	ITEMID_STAMP_DATE,
#endif
#if (MENU_GENERAL_DATE_LOGO_STAMP_LOGO_EN)
	ITEMID_STAMP_LOGO,
#endif
#if (MENU_GENERAL_DATE_LOGO_STAMP_OFF_EN)
	ITEMID_STAMP_OFF,
#endif
#endif

#if MENU_GENERAL_GPS_STAMP_EN
	ITEMID_GPS_STAMP,
	ITEMID_GPS_STAMP_ON,
	ITEMID_GPS_STAMP_OFF,
#endif

#if MENU_GENERAL_SPEED_STAMP_EN
	ITEMID_SPEED_STAMP,
	ITEMID_SPEED_STAMP_ON,
	ITEMID_SPEED_STAMP_OFF,
#endif

#if MENU_GENERAL_MOTION_DTC_EN
    ITEMID_MOTION_DETECT,
#if (MENU_GENERAL_MOTION_DTC_OFF_EN)
    ITEMID_MOTION_DETECT_OFF,
#endif
#if (MENU_GENERAL_MOTION_DTC_LOW_EN)
    ITEMID_MOTION_DETECT_LOW,
#endif
#if (MENU_GENERAL_MOTION_DTC_MID_EN)
    ITEMID_MOTION_DETECT_MID,
#endif
#if (MENU_GENERAL_MOTION_DTC_HIGH_EN)
    ITEMID_MOTION_DETECT_HIGH,
#endif
#endif

#if (MENU_GENERAL_POWERON_GSENSOR_EN)
    ITEMID_GSENSOR_POWERON_SENSITIVITY,
#if (MENU_GENERAL_POWERON_GSENSOR_OFF_EN)
    ITEMID_GSENSOR_POWERON_SENSITIVITY_OFF,
#endif
#if (MENU_GENERAL_POWER_ON_GSENSOR_LEVEL0_EN)
    ITEMID_GSENSOR_POWERON_SENSITIVITY_L0,
#endif
#if (MENU_GENERAL_POWER_ON_GSENSOR_LEVEL1_EN)
    ITEMID_GSENSOR_POWERON_SENSITIVITY_L1,
#endif
#if (MENU_GENERAL_POWER_ON_GSENSOR_LEVEL2_EN)
    ITEMID_GSENSOR_POWERON_SENSITIVITY_L2,
#endif
#endif

#if (MENU_GENERAL_WIFI_EN)
    ITEMID_WIFI_MODE,
#if (MENU_GENERAL_WIFI_ON_EN)
    ITEMID_WIFI_MODE_ON,
#endif
#if (MENU_GENERAL_WIFI_OFF_EN)
    ITEMID_WIFI_MODE_OFF,
#endif
#endif

#if (MENU_GENERAL_PQ_CONTRAST_EN)
    ITMEID_PQ_CONTRAST,
    ITMEID_PQ_CONTRAST_DEC,
    ITMEID_PQ_CONTRAST_INC,
#endif

#if (MENU_GENERAL_PQ_BRIGHTNESS_EN)
    ITEMID_PQ_BRIGHTNESS,
    ITEMID_PQ_BRIGHTNESS_DEC,
    ITEMID_PQ_BRIGHTNESS_INC,
#endif

#if (MENU_GENERAL_PQ_SATURATION_EN)
    ITEMID_PQ_SATURATION,
    ITEMID_PQ_SATURATION_DEC,
    ITEMID_PQ_SATURATION_INC,
#endif

#if (MENU_GENERAL_PQ_COLORTEMP_EN)
    ITEMID_PQ_COLORTEMP,
    ITEMID_PQ_COLORTEMP_OFF,
    ITEMID_PQ_COLORTEMP_MODE1,
    ITEMID_PQ_COLORTEMP_MODE2,
    ITEMID_PQ_COLORTEMP_MODE3,
    ITEMID_PQ_COLORTEMP_MODE4,
#endif

#if 1//(MENU_GENERAL_SYSTEM_SETTINGS_EN)
    ITEMID_SYSTEM_SETTINGS,
#endif

    ITEMID_GENERAL_END

} GENERALSETTINGITEMID;

typedef enum {

#if MENU_MANUAL_SCENE_EN
    ITEMID_SCENE        =  ITEMID_GENERAL_END,
#if (MENU_MANUAL_SCENE_AUTO_EN)
    ITEMID_SCENE_AUTO     ,
#endif
#if (MENU_MANUAL_SCENE_SPORT_EN)
    ITEMID_SCENE_SPORTS   ,
#endif
#if (MENU_MANUAL_SCENE_PORTRAIT_EN)
    ITEMID_SCENE_PORTRAIT   ,
#endif
#if (MENU_MANUAL_SCENE_LANDSCAPE_EN)
    ITEMID_SCENE_LANDSCAPE   ,
#endif
#if (MENU_MANUAL_SCENE_TWILIGHT_PORTRAIT_EN)
    ITEMID_SCENE_TWILIGHT_PORTRAIT ,
#endif
#if (MENU_MANUAL_SCENE_TWILIGHT_EN)
    ITEMID_SCENE_TWILIGHT ,
#endif
#if (MENU_MANUAL_SCENE_SNOW_EN)
    ITEMID_SCENE_SNOW     ,
#endif
#if (MENU_MANUAL_SCENE_BEACH_EN)
    ITEMID_SCENE_BEACH    ,
#endif
#if (MENU_MANUAL_SCENE_FIREWORKS_EN)
    ITEMID_SCENE_FIREWORKS,
#endif
#endif

#if MENU_MANUAL_EV_EN
    ITEMID_EV = ITEMID_GENERAL_END,
#if (MENU_MANUAL_EV_N20_EN)
    ITEMID_EV_N20,
#endif
#if (MENU_MANUAL_EV_N17_EN)
    ITEMID_EV_N17,
#endif
#if (MENU_MANUAL_EV_N13_EN)
    ITEMID_EV_N13,
#endif
#if (MENU_MANUAL_EV_N10_EN)
    ITEMID_EV_N10,
#endif
#if (MENU_MANUAL_EV_N07_EN)
    ITEMID_EV_N07,
#endif
#if (MENU_MANUAL_EV_N03_EN)
    ITEMID_EV_N03,
#endif
#if (MENU_MANUAL_EV_00_EN)
    ITEMID_EV_00,
#endif
#if (MENU_MANUAL_EV_P03_EN)
    ITEMID_EV_P03,
#endif
#if (MENU_MANUAL_EV_P07_EN)
    ITEMID_EV_P07,
#endif
#if (MENU_MANUAL_EV_P10_EN)
    ITEMID_EV_P10,
#endif
#if (MENU_MANUAL_EV_P13_EN)
    ITEMID_EV_P13,
#endif
#if (MENU_MANUAL_EV_P17_EN)
    ITEMID_EV_P17,
#endif
#if (MENU_MANUAL_EV_P20_EN)
    ITEMID_EV_P20,
#endif
#endif

#if MENU_MANUAL_ISO_EN
    ITEMID_ISO,
#if (MENU_MANUAL_ISO_AUTO_EN)
    ITEMID_ISO_AUTO,
#endif
#if (MENU_MANUAL_ISO_100_EN)
    ITEMID_ISO_100,
#endif
#if (MENU_MANUAL_ISO_200_EN)
    ITEMID_ISO_200,
#endif
#if (MENU_MANUAL_ISO_400_EN)
    ITEMID_ISO_400,
#endif
#if (MENU_MANUAL_ISO_800_EN)
    ITEMID_ISO_800,
#endif
#if (MENU_MANUAL_ISO_1600_EN)
    ITEMID_ISO_1600,
#endif
#if (MENU_MANUAL_ISO_3200_EN)
    ITEMID_ISO_3200,
#endif
#endif

#if MENU_MANUAL_WB_EN
    ITEMID_WB,
#if (MENU_MANUAL_WB_AUTO_EN)
    ITEMID_WB_AUTO,
#endif
#if (MENU_MANUAL_WB_DAYLIGHT_EN)
    ITEMID_WB_DAYLIGHT,
#endif
#if (MENU_MANUAL_WB_CLOUDY_EN)
    ITEMID_WB_CLOUDY,
#endif
#if (MENU_MANUAL_WB_FLUORESCENT1_EN)
    ITEMID_WB_FLUORESCENT1,
#endif
#if (MENU_MANUAL_WB_FLUORESCENT2_EN)
    ITEMID_WB_FLUORESCENT2,
#endif
#if (MENU_MANUAL_WB_FLUORESCENT3_EN)
    ITEMID_WB_FLUORESCENT3,
#endif
#if (MENU_MANUAL_WB_INCANDESCENT_EN)
    ITEMID_WB_INCANDESCENT,
#endif
#if (MENU_MANUAL_WB_FLASH_EN)
    ITEMID_WB_FLASH,
#endif
#if (MENU_MANUAL_WB_ONEPUSH_EN)
    ITEMID_WB_ONEPUSH,
#endif
#if (MENU_MANUAL_WB_ONE_PUSH_SET_EN)
    ITEMID_WB_ONE_PUSH_SET,
#endif
#endif

#if MENU_MANUAL_COLOR_EN
    ITEMID_COLOR,
#if (MENU_MANUAL_COLOR_NATURAL_EN)
    ITEMID_COLOR_NATURAL,
#endif
#if (MENU_MANUAL_COLOR_VIVID_EN)
    ITEMID_COLOR_VIVID,
#endif
#if (MENU_MANUAL_COLOR_PALE_EN)
    ITEMID_COLOR_PALE,
#endif
#endif

#if MENU_MANUAL_EFFECT_EN
    ITEMID_EFFECT,
#if (MENU_MANUAL_EFFECT_NORMAL_EN)
    ITEMID_EFFECT_NORMAL,
#endif
#if (MENU_MANUAL_EFFECT_SEPIA_EN)
    ITEMID_EFFECT_SEPIA,
#endif
#if (MENU_MANUAL_EFFECT_BLACK_WHITE_EN)
    ITEMID_EFFECT_BLACK_WHITE,
#endif
#if (MENU_MANUAL_EFFECT_EMBOSS_EN)
    ITEMID_EFFECT_EMBOSS,
#endif
#if (MENU_MANUAL_EFFECT_NEGATIVE_EN)
    ITEMID_EFFECT_NEGATIVE,
#endif
#if (MENU_MANUAL_EFFECT_SKETCH_EN)
    ITEMID_EFFECT_SKETCH,
#endif
#if (MENU_MANUAL_EFFECT_OIL_EN)
    ITEMID_EFFECT_OIL,
#endif
#if (MENU_MANUAL_EFFECT_CRAYON_EN)
    ITEMID_EFFECT_CRAYON,
#endif
#if (MENU_MANUAL_EFFECT_BEAUTY_EN)
    ITEMID_EFFECT_BEAUTY,
#endif
#endif

    ITEMID_CONTRAST,
    ITEMID_CONTRAST_INC,
    ITEMID_CONTRAST_DEC,

    ITEMID_SATURATION,
    ITEMID_SATURATION_INC,
    ITEMID_SATURATION_DEC,

    ITEMID_SHARPNESS,
    ITEMID_SHARPNESS_INC,
    ITEMID_SHARPNESS_DEC,

    ITEMID_GAMMA,
    ITEMID_GAMMA_INC,
    ITEMID_GAMMA_DEC,
    
    MAX_MANUALSETTINGITEMID
}MANUALSETTINGITEMID;

typedef enum {
    ITEMID_MEDIA_SELECT     =  MAX_MANUALSETTINGITEMID,
    ITEMID_MEDIA_SD_CARD,
    ITEMID_MEDIA_INTERNAL,
    ITEMID_FORMAT_SD_CARD,
    ITEMID_FORMAT_CARD_YES,
    ITEMID_FORMAT_CARD_NO,
    ITEMID_FORMAT_INTMEM,
    ITEMID_FORMAT_INTMEM_YES,
    ITEMID_FORMAT_INTMEM_NO,
    ITEMID_SD_CARD_INFO,
    ITEMID_CARD_TIME_LEFT,
    ITEMID_CARD_PHOTO_LEFT,
    ITEMID_INTMEM_INFO,
    ITEMID_INT_TIME_LEFT,
    ITEMID_INT_PHOTO_LEFT,

    ITEMID_MEDIA_END
} MEDIATOOLITEMID;

typedef enum {
    ITEMID_QUICKM_DELETE= ITEMID_MEDIA_END,
    ITEMID_QUICKM_DEL_YES,
    ITEMID_QUICKM_DEL_NO,
    
    ITEMID_QUICKM_PROTECT,
    ITEMID_QUICKM_PROTECT_YES,
    ITEMID_QUICKM_PROTECT_NO,
    
    ITEMID_CUT,
    ITEMID_CUT_YES,
    ITEMID_CUT_NO,
    
    ITEMID_ROTATE,
    ITEMID_ROTATE_LEFT,
    ITEMID_ROTATE_RIGHT,
    ITEMID_ROTATE_OK,
    ITEMID_ROTATE_CANCEL,
    
    ITEMID_RESIZE,
    ITEMID_RESIZE_SIZE_14M,
    ITEMID_RESIZE_SIZE_12M,
    ITEMID_RESIZE_SIZE_8M,
    ITEMID_RESIZE_SIZE_5M,
    ITEMID_RESIZE_SIZE_3M,
    ITEMID_RESIZE_SIZE_2M,
    ITEMID_RESIZE_SIZE_1_2M,
    ITEMID_RESIZE_SIZE_VGA,
    
    ITEMID_TRIMMING,
    ITEMID_TRIMMING_OK,
    ITEMID_TRIMMING_CANCEL,
    
    ITEMID_SLIDE_SHOW_FILES,
#if (MENU_PLAYBACK_SLIDESHOW_FILE_ALL_EN)    
    ITEMID_FILES_ALL,
#endif
#if (MENU_PLAYBACK_SLIDESHOW_FILE_STILL_EN)    
    ITEMID_FILES_STILL,
#endif
#if (MENU_PLAYBACK_SLIDESHOW_FILE_MOVIE_EN)    
    ITEMID_FILES_MOVIE,
#endif    

    ITEMID_SLIDE_SHOW_EFFECTS,
#if (MENU_PLAYBACK_SLIDESHOW_EFFECT_SIMPLE_EN)
    ITEMID_SLIDE_EFFECTS_SIMPLE,
#endif
#if (MENU_PLAYBACK_SLIDESHOW_EFFECT_NOSTALGIC_EN)    
    ITEMID_SLIDE_EFFECTS_NOSTALGIC,
#endif
#if (MENU_PLAYBACK_SLIDESHOW_EFFECT_STYLISH_EN)    
    ITEMID_SLIDE_EFFECTS_STYLISH,
#endif
#if (MENU_PLAYBACK_SLIDESHOW_EFFECT_ACTIVE_EN)    
    ITEMID_SLIDE_EFFECTS_ACTIVE,
#endif
    
    ITEMID_SLIDE_SHOW_MUSIC,
#if (MENU_PLAYBACK_SLIDESHOW_MUSIC_ON_EN)
    ITEMID_MUSIC_ON,
#endif
#if (MENU_PLAYBACK_SLIDESHOW_MUSIC_OFF_EN)    
    ITEMID_MUSIC_OFF,
#endif
    
    ITEMID_VOLUME,

#if (MENU_PLAYBACK_VOLUME_LV0_EN)
    ITEMID_VOLUME_00,
#endif
#if (MENU_PLAYBACK_VOLUME_LV1_EN)    
    ITEMID_VOLUME_01,
#endif
#if (MENU_PLAYBACK_VOLUME_LV2_EN)    
    ITEMID_VOLUME_02,
#endif
#if (MENU_PLAYBACK_VOLUME_LV3_EN)    
    ITEMID_VOLUME_03,
#endif
#if (MENU_PLAYBACK_VOLUME_LV4_EN)    
    ITEMID_VOLUME_04,
#endif
#if (MENU_PLAYBACK_VOLUME_LV5_EN)    
    ITEMID_VOLUME_05,
#endif
#if (MENU_PLAYBACK_VOLUME_LV6_EN)    
    ITEMID_VOLUME_06,
#endif
#if (MENU_PLAYBACK_VOLUME_LV7_EN)    
    ITEMID_VOLUME_07,
#endif
#if (MENU_PLAYBACK_VOLUME_LV8_EN)    
    ITEMID_VOLUME_08,
#endif
#if (MENU_PLAYBACK_VOLUME_LV9_EN)    
    ITEMID_VOLUME_09,
#endif    
#if (MENU_PLAYBACK_VOLUME_LV10_EN)
    ITEMID_VOLUME_10,
#endif

    ITEMID_VOLUME_MAX,

    ITEMID_SHOW_VIDEO_TYPE,
#if (MENU_PLAYBACK_VIDEO_TYPE_NORMAL_EN)
    ITEMID_VIDEO_TYPE_NORMAL,
#endif
#if (MENU_PLAYBACK_VIDEO_TYPE_PARKING_EN)    
    ITEMID_VIDEO_TYPE_PARKING,
#endif
#if (MENU_PLAYBACK_VIDEO_TYPE_EMERGENCY_EN)    
    ITEMID_VIDEO_TYPE_EMERGENCY,
#endif

    ITEMID_SHOW_VIDEO_CAMID,
#if (MENU_PLAYBACK_VIDEO_CAMID_1ST_EN)
    ITEMID_VIDEO_CAMID_1ST,
#endif
#if (MENU_PLAYBACK_VIDEO_CAMID_2ND_EN)    
    ITEMID_VIDEO_CAMID_2ND,
#endif
#if (MENU_PLAYBACK_VIDEO_CAMID_3RD_EN)    
    ITEMID_VIDEO_CAMID_3RD,
#endif
#if (MENU_PLAYBACK_VIDEO_CAMID_4TH_EN)    
    ITEMID_VIDEO_CAMID_4TH,
#endif

}PLAYBACKITEMID;

//Menu Settting
typedef enum {
    VIDEOREC_MODE = 0 ,
    CAPTURE_MODE   ,
    SLIDESHOW_MODE ,
    JPGPB_MODE     ,
    MOVPB_MODE     ,
    AUDPB_MODE     ,
    JPGPB_MOVPB_MODE ,
    DEFAULT_MODE
} OP_MODE_SETTING;

typedef enum {
#if (MENU_STILL_SIZE_30M_EN)
    IMAGE_SIZE_30M,     ///< 6400*4800
#endif
#if (MENU_STILL_SIZE_14M_EN)
    IMAGE_SIZE_14M,     ///< 4352*3264
#endif
#if (MENU_STILL_SIZE_12M_EN)
    IMAGE_SIZE_12M,     ///< 4000*3000
#endif
#if (MENU_STILL_SIZE_8M_EN)
    IMAGE_SIZE_8M,      ///< 3264*2448
#endif
#if (MENU_STILL_SIZE_6M_WIDE_EN)
    IMAGE_SIZE_6M_WIDE, ///<
#endif
#if (MENU_STILL_SIZE_6M_EN)
    IMAGE_SIZE_6M,      ///<
#endif
#if (MENU_STILL_SIZE_5M_EN)
    IMAGE_SIZE_5M,      ///< 2560*1920
#endif
#if (MENU_STILL_SIZE_3M_EN)
    IMAGE_SIZE_3M,      ///< 2048*1536
#endif
#if (MENU_STILL_SIZE_2M_WIDE_EN)
    IMAGE_SIZE_2M,      ///< 1920*1080
#endif
#if (MENU_STILL_SIZE_1d2M_EN)
    IMAGE_SIZE_1_2M,    ///< 1280*960
#endif
#if (MENU_STILL_SIZE_VGA_EN)
    IMAGE_SIZE_VGA,     ///< 640*480
#endif

    IMAGE_SIZE_NUM,
 } IMAGESIZE_SETTING;

typedef enum{
    #if MENU_MOVIE_SIZE_4K_25P_EN
    MOVIE_SIZE_4K_25P,
    #endif
    #if(MENU_MOVIE_SIZE_1440_30P_EN)
    MOVIE_SIZE_1440_30P,
    #endif
    #if MENU_MOVIE_SIZE_SHD_30P_EN
    MOVIE_SIZE_SHD_30P,
    #endif
    #if MENU_MOVIE_SIZE_SHD_25P_EN
    MOVIE_SIZE_SHD_25P,
    #endif
    #if MENU_MOVIE_SIZE_1080P_30_HDR_EN
    MOVIE_SIZE_1080_30P_HDR,
    #endif
    #if MENU_MOVIE_SIZE_1080_60P_EN
    MOVIE_SIZE_1080_60P,
    #endif
    #if MENU_MOVIE_SIZE_1080_25P_EN
    MOVIE_SIZE_1080_25P,
    #endif
    #if MENU_MOVIE_SIZE_1080P_EN
    MOVIE_SIZE_1080P,
    MOVIE_SIZE_1080_30P = MOVIE_SIZE_1080P,
    #endif
    #if (MENU_MOVIE_SIZE_960P_30P_EN)
    MOVIE_SIZE_960P_30P,
    #endif
    #if MENU_MOVIE_SIZE_900P_30P_EN
    MOVIE_SIZE_900P_30P,
    #endif
    #if MENU_MOVIE_SIZE_720P_EN
    MOVIE_SIZE_720P,
    MOVIE_SIZE_720_30P = MOVIE_SIZE_720P,
    #endif
    #if MENU_MOVIE_SIZE_720_120P_EN
    MOVIE_SIZE_720_120P,
    #endif
    #if MENU_MOVIE_SIZE_720_60P_EN
    MOVIE_SIZE_720_60P,
    #endif
    #if MENU_MOVIE_SIZE_720_50P_EN
    MOVIE_SIZE_720_50P,
    #endif
    #if MENU_MOVIE_SIZE_VGA30P_EN
    MOVIE_SIZE_VGA30P,
    MOVIE_SIZE_VGA_30P = MOVIE_SIZE_VGA30P,
    #endif
    MOVIE_SIZE_NUM,
 } MOVIESIZE_SETTING;

 typedef enum {
    SLOWMOTION_SIZE_WIDE_720P_60 = 0,
    SLOWMOTION_SIZE_WIDE_480P_120,
    SLOWMOTION_SIZE_720P_60,
    SLOWMOTION_SIZE_480P_120,
    SLOWMOTION_SIZE_NUM,
    SLOWMOTION_SIZE_DEFAULT = 0
 } SLOWMOTIONSIZE_SETTING;

typedef enum{
    SLOWMOTION_X1 = 0,
    SLOWMOTION_X2,
    SLOWMOTION_X4,
    SLOWMOTION_X8,
    SLOWMOTION_NUM,

    SLOWMOTION_DEFAULT = 0
}SLOWMOTION_SETTING;


typedef enum{
#if (MENU_STILL_QUALITY_SUPER_FINE_EN || MENU_MOVIE_QUALITY_SUPER_FINE_EN)
    QUALITY_SUPER_FINE,
#endif
#if (MENU_STILL_QUALITY_FINE_EN || MENU_MOVIE_QUALITY_FINE_EN)
    QUALITY_FINE,
#endif
    QUALITY_NUM,
    QUALITY_DEFAULT = 0
}QUALITY_SETTING;

typedef enum{
#if (MENU_MANUAL_SCENE_AUTO_EN)
    SCENE_AUTO,
#endif
#if (MENU_MANUAL_SCENE_SPORT_EN)
    SCENE_SPORT,
#endif
#if (MENU_MANUAL_SCENE_PORTRAIT_EN)
    SCENE_PORTRAIT,
#endif
#if (MENU_MANUAL_SCENE_LANDSCAPE_EN)
    SCENE_LANDSCAPE,
#endif
#if (MENU_MANUAL_SCENE_TWILIGHT_PORTRAIT_EN)
    SCENE_TWILIGHT_PORTRAIT,
#endif
#if (MENU_MANUAL_SCENE_TWILIGHT_EN)
    SCENE_TWILIGHT,
#endif
#if (MENU_MANUAL_SCENE_SNOW_EN)
    SCENE_SNOW,
#endif
#if (MENU_MANUAL_SCENE_BEACH_EN)
    SCENE_BEACH,
#endif
#if (MENU_MANUAL_SCENE_FIREWORKS_EN)
    SCENE_FIREWORKS,
#endif

    SCENE_NUM,
 } SCENE_SETTING;

typedef enum {
#if (MENU_MANUAL_EV_N20_EN)
    EVVALUE_N20 ,
#endif
#if (MENU_MANUAL_EV_N17_EN)
    EVVALUE_N17 ,
#endif
#if (MENU_MANUAL_EV_N15_EN)
    EVVALUE_N15 ,
#endif
#if (MENU_MANUAL_EV_N13_EN)
    EVVALUE_N13 ,
#endif
#if (MENU_MANUAL_EV_N10_EN)
    EVVALUE_N10 ,
#endif
#if (MENU_MANUAL_EV_N07_EN)
    EVVALUE_N07 ,
#endif
#if (MENU_MANUAL_EV_N05_EN)
    EVVALUE_N05 ,
#endif
#if (MENU_MANUAL_EV_N03_EN)
    EVVALUE_N03 ,
#endif
//#if (MENU_MANUAL_EV_00_EN)    // always exist
    EVVALUE_00  ,
//#endif
#if (MENU_MANUAL_EV_P03_EN)
    EVVALUE_P03 ,
#endif
#if (MENU_MANUAL_EV_P05_EN)
    EVVALUE_P05 ,
#endif
#if (MENU_MANUAL_EV_P07_EN)
    EVVALUE_P07 ,
#endif
#if (MENU_MANUAL_EV_P10_EN)
    EVVALUE_P10 ,
#endif
#if (MENU_MANUAL_EV_P13_EN)
    EVVALUE_P13 ,
#endif
#if (MENU_MANUAL_EV_P15_EN)
    EVVALUE_P15 ,
#endif
#if (MENU_MANUAL_EV_P17_EN)
    EVVALUE_P17 ,
#endif
#if (MENU_MANUAL_EV_P20_EN)
    EVVALUE_P20 ,
#endif

    EVVALUE_NUM ,
}EVVALUE_SETTING;

typedef enum {
#if (MENU_MANUAL_ISO_AUTO_EN)
    ISO_AUTO,
#endif
//  ISO_80,
#if (MENU_MANUAL_ISO_100_EN)
    ISO_100,
#endif
#if (MENU_MANUAL_ISO_200_EN)
    ISO_200,
#endif
#if (MENU_MANUAL_ISO_400_EN)
    ISO_400,
#endif
#if (MENU_MANUAL_ISO_800_EN)
    ISO_800,
#endif
#if (MENU_MANUAL_ISO_1200_EN)
    ISO_1200,
#endif
#if (MENU_MANUAL_ISO_1600_EN)
    ISO_1600,
#endif
#if (MENU_MANUAL_ISO_3200_EN)
    ISO_3200,
#endif

    ISO_NUM,
} ISOMode_SETTING;

typedef enum {
#if (MENU_MANUAL_WB_AUTO_EN)
    WB_AUTO,
#endif
#if (MENU_MANUAL_WB_DAYLIGHT_EN)
    WB_DAYLIGHT,
#endif
#if (MENU_MANUAL_WB_CLOUDY_EN)
    WB_CLOUDY,
#endif
#if (MENU_MANUAL_WB_FLUORESCENT1_EN)
    WB_FLUORESCENT1,
    WB_FLUORESCENT = WB_FLUORESCENT1,
#endif
#if (MENU_MANUAL_WB_FLUORESCENT2_EN)
    WB_FLUORESCENT2,
#endif
#if (MENU_MANUAL_WB_FLUORESCENT3_EN)
    WB_FLUORESCENT3,
#endif
#if (MENU_MANUAL_WB_INCANDESCENT_EN)
    WB_INCANDESCENT,
#endif
#if (MENU_MANUAL_WB_FLASH_EN)
    WB_FLASH,
#endif
#if (MENU_MANUAL_WB_ONEPUSH_EN)
    WB_ONEPUSH,
#endif
#if (MENU_MANUAL_WB_ONE_PUSH_SET_EN)
    WB_ONE_PUSH_SET,
#endif
#if (MENU_MANUAL_WB_UNDERWATER)
    WB_UNDERWATER,
#endif

    WB_NUM,
}WB_SETTING;

typedef enum{
#if (MENU_MANUAL_COLOR_NATURAL_EN)
    COLOR_NATURAL,
#endif
#if (MENU_MANUAL_COLOR_VIVID_EN)
    COLOR_VIVID,
#endif
#if (MENU_MANUAL_COLOR_PALE_EN)
    COLOR_PALE,
#endif

    COLOR_NUM,
}COLOR_SETTING;

typedef enum {
#if (MENU_MANUAL_EFFECT_NORMAL_EN)
    EFFECT_NORMAL,
#endif
#if (MENU_MANUAL_EFFECT_SEPIA_EN)
    EFFECT_SEPIA,
#endif
#if (MENU_MANUAL_EFFECT_BLACK_WHITE_EN)
    EFFECT_BLACK_WHITE,
#endif
#if (MENU_MANUAL_EFFECT_EMBOSS_EN)
    EFFECT_EMBOSS,
#endif
#if (MENU_MANUAL_EFFECT_NEGATIVE_EN)
    EFFECT_NEGATIVE,
#endif
#if (MENU_MANUAL_EFFECT_SKETCH_EN)
    EFFECT_SKETCH,
#endif
#if (MENU_MANUAL_EFFECT_OIL_EN)
    EFFECT_OIL,
#endif
#if (MENU_MANUAL_EFFECT_CRAYON_EN)
    EFFECT_CRAYON,
#endif
#if (MENU_MANUAL_EFFECT_BEAUTY_EN)
    EFFECT_BEAUTY,
#endif

    EFFECT_NUM,
}EFFECT_SETTING;

typedef enum{
    MEDIA_SETTING_SD_CARD,
    MEDIA_SETTING_SD_CARD1,
    MEDIA_SETTING_INTERNAL,
    MEDIA_SETTING_SD_CARD_ERR,
    MEDIA_SETTING_INTERNAL_ERR,
    MEDIA_SETTING_FACFAT,
    MEDIA_SETTING_USERFAT,
    MEDIA_SETTING_NUM,
    MEDIA_SETTING_DEFAULT = 0
}MEDIASETING_SETTING;

typedef enum{
    WDR_OFF,
    WDR_ON,
    WDR_NUM,
    WDR_DEFAULT = 0
} WDR_MODE;

typedef enum{
#if (MENU_MOVIE_MIC_SEN_STANDARD_EN)
    MIC_SEN_STANDARD,
#endif
#if (MENU_MOVIE_MIC_SEN_LOW_EN)
    MIC_SEN_LOW,
#endif

    MIC_SEN_NUM,
}MIC_SENSITIVITY_SETTING;

typedef enum{
#if (MENU_MOVIE_PRE_RECORD_ON_EN)
    MOVIE_PRE_RECORD_ON,
#endif
#if (MENU_MOVIE_PRE_RECORD_OFF_EN)
    MOVIE_PRE_RECORD_OFF,
#endif
    MOVIE_PRE_RECORD_NUM,
}MOVIE_PRE_RECORD_SETTING;

typedef enum {
#if (MENU_VIDEO_TIMELAPSE_MODE_OFF_EN)
    MOVIE_VR_TIMELAPSE_OFF  = 0,
#endif
#if (MENU_VIDEO_TIMELAPSE_MODE_1SEC_EN)
    MOVIE_VR_TIMELAPSE_1SEC,
#endif
#if (MENU_VIDEO_TIMELAPSE_MODE_5SEC_EN)
    MOVIE_VR_TIMELAPSE_5SEC,
#endif
#if (MENU_VIDEO_TIMELAPSE_MODE_10SEC_EN)
    MOVIE_VR_TIMELAPSE_10SEC,
#endif
#if (MENU_VIDEO_TIMELAPSE_MODE_30SEC_EN)
    MOVIE_VR_TIMELAPSE_30SEC,
#endif
#if (MENU_VIDEO_TIMELAPSE_MODE_60SEC_EN)
    MOVIE_VR_TIMELAPSE_60SEC,
#endif
    MOVIE_VR_TIMELAPSE_NUM,
    MOVIE_VR_TIMELAPSE_DEFAULT = 0
} MOVIE_VR_TIMELAPSE;

typedef enum{
    MOVIE_PARKING_MODE_ON,
    MOVIE_PARKING_MODE_OFF,
    MOVIE_PARKING_MODE_NUM,
} MOVIE_PARKING_MODE;

typedef enum{
#if (MENU_PLAYBACK_VOLUME_LV0_EN)
    VOLUME_00,
#endif
#if (MENU_PLAYBACK_VOLUME_LV1_EN)
    VOLUME_01 ,
#endif
#if (MENU_PLAYBACK_VOLUME_LV2_EN)
    VOLUME_02 ,
#endif
#if (MENU_PLAYBACK_VOLUME_LV3_EN)
    VOLUME_03 ,
#endif
#if (MENU_PLAYBACK_VOLUME_LV4_EN)
    VOLUME_04 ,
#endif
#if (MENU_PLAYBACK_VOLUME_LV5_EN)
    VOLUME_05 ,
#endif
#if (MENU_PLAYBACK_VOLUME_LV6_EN)
    VOLUME_06 ,
#endif
#if (MENU_PLAYBACK_VOLUME_LV7_EN)
    VOLUME_07 ,
#endif
#if (MENU_PLAYBACK_VOLUME_LV8_EN)
    VOLUME_08 ,
#endif
#if (MENU_PLAYBACK_VOLUME_LV9_EN)
    VOLUME_09 ,
#endif
#if (MENU_PLAYBACK_VOLUME_LV10_EN)
    VOLUME_10 ,
#endif

	VOLUME_NUM,
	VOLUME_DEFAULT = 0
}VOLUME_SETTING;

typedef enum{
#if (MENU_GENERAL_BEEP_ON_EN)
    BEEP_ON,
#endif
#if (MENU_GENERAL_BEEP_OFF_EN)
    BEEP_OFF,
#endif

    BEEP_NUM,
    BEEP_DEFAULT = 0
}BEEP_SETTING;

typedef enum{
    LDWS_EN_ON = 0,
    LDWS_EN_OFF,
    LDWS_EN_DEFAULT = LDWS_EN_OFF
} LDWS_EN_SETTING;

typedef enum{
    FCWS_EN_ON = 0,
    FCWS_EN_OFF,
    FCWS_EN_DEFAULT = FCWS_EN_OFF
} FCWS_EN_SETTING;

typedef enum{
    SAG_EN_ON = 0,
    SAG_EN_OFF,
    SAG_EN_DEFAULT = SAG_EN_OFF
} SAG_EN_SETTING;

typedef enum{
    HDR_EN_ON = 0,
    HDR_EN_OFF,
    HDR_EN_DEFAULT = HDR_EN_OFF
} HDR_EN_SETTING;

typedef enum{
    WNR_EN_OFF = 0,
    WNR_EN_ON,
    WNR_EN_DEFAULT = WNR_EN_OFF
} WNR_EN_SETTING;

typedef enum{
#if (MENU_STILL_BURST_SHOT_OFF_EN)
    BURST_SHOT_OFF,
#endif
#if (MENU_STILL_BURST_SHOT_LO_EN)
    BURST_SHOT_LO,
#endif
#if (MENU_STILL_BURST_SHOT_MID_EN)
    BURST_SHOT_MID,
#endif
#if (MENU_STILL_BURST_SHOT_HI_EN)
    BURST_SHOT_HI,
#endif
    BURST_SHOT_NUM,
    BURST_SHOT_DEFAULT = 0
}BURSTSHOT_SETTING;

typedef enum{
#if (MENU_GENERAL_LANGUAGE_ENGLISH_EN)
    LANGUAGE_ENGLISH,
#endif
#if (MENU_GENERAL_LANGUAGE_SPANISH_EN)
    LANGUAGE_SPANISH,
#endif
#if (MENU_GENERAL_LANGUAGE_PORTUGUESE_EN)
    LANGUAGE_PORTUGUESE,
#endif
#if (MENU_GENERAL_LANGUAGE_RUSSIAN_EN)
    LANGUAGE_RUSSIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_SCHINESE_EN)
    LANGUAGE_SCHINESE,
#endif
#if (MENU_GENERAL_LANGUAGE_TCHINESE_EN)
    LANGUAGE_TCHINESE,
#endif
#if (MENU_GENERAL_LANGUAGE_GERMAN_EN)
    LANGUAGE_GERMAN,
#endif
#if (MENU_GENERAL_LANGUAGE_ITALIAN_EN)
    LANGUAGE_ITALIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_LATVIAN_EN)
    LANGUAGE_LATVIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_POLISH_EN)
    LANGUAGE_POLISH,
#endif
#if (MENU_GENERAL_LANGUAGE_ROMANIAN_EN)
    LANGUAGE_ROMANIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_SLOVAK_EN)
    LANGUAGE_SLOVAK,
#endif
#if (MENU_GENERAL_LANGUAGE_UKRANINIAN_EN)
    LANGUAGE_UKRANINIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_FRENCH_EN)
    LANGUAGE_FRENCH,
#endif
#if (MENU_GENERAL_LANGUAGE_JAPANESE_EN)
    LANGUAGE_JAPANESE,
#endif
#if (MENU_GENERAL_LANGUAGE_KOREAN_EN)
    LANGUAGE_KOREAN,
#endif
#if (MENU_GENERAL_LANGUAGE_CZECH_EN)
    LANGUAGE_CZECH,
#endif

    LANGUAGE_NUM,
}LANGUAGE_SETTING;

typedef enum{
#if (MENU_GENERAL_DATE_FORMAT_NONE_EN)
    DATETIME_SETUP_NONE = 0,
#endif
#if (MENU_GENERAL_DATE_FORMAT_YMD_EN)
    DATETIME_SETUP_YMD,
#endif
#if (MENU_GENERAL_DATE_FORMAT_MDY_EN)
    DATETIME_SETUP_MDY,
#endif
#if (MENU_GENERAL_DATE_FORMAT_DMY_EN)
    DATETIME_SETUP_DMY,
#endif
    DATETIME_SETUP_NUM,
    DATETIME_SETUP_DEFAULT = 0
}DATETIMESETUP_SETTING;

typedef enum {
#if (MENU_GENERAL_DATE_LOGO_STAMP_DATE_LOGO_EN)
    DATELOGO_STAMP,
#endif
#if (MENU_GENERAL_DATE_LOGO_STAMP_DATE_EN)
    DATE_STAMP,
#endif
#if (MENU_GENERAL_DATE_LOGO_STAMP_LOGO_EN)
    LOGO_STAMP,
#endif
#if (MENU_GENERAL_DATE_LOGO_STAMP_OFF_EN)
    OFF_STAMP,
#endif
    DATALOGO_SETUP_NUM,
    DATALOGO_SETUP_DEFAULT = 0
}DATELOGOSTAMP_SETTING;

typedef enum{
#if (MENU_GENERAL_AUTO_POWEROFF_NEVER_EN)
    AUTO_POWER_OFF_NEVER,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_15SEC_EN)
    AUTO_POWER_OFF_15SEC,
#endif

#if (MENU_GENERAL_AUTO_POWEROFF_30SEC_EN)
    AUTO_POWER_OFF_30SEC,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_1MIN_EN)
    AUTO_POWER_OFF_1MIN,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_2MIN_EN)
    AUTO_POWER_OFF_2MINS,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_3MIN_EN)
    AUTO_POWER_OFF_3MINS,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_5MIN_EN)
    AUTO_POWER_OFF_5MINS,
#endif

    AUTO_POWER_OFF_NUM,
}AUTO_POWER_OFF_SETTING;

typedef enum{
    SLIDESHOW_DISABLE,
    SLIDESHOW_ENABLE,
    SLIDESHOW_NUM,
    SLIDESHOW_DEFAULT = 0
}SLIDESHOW_SETTING;

typedef enum{
#if (MENU_PLAYBACK_SLIDESHOW_FILE_ALL_EN)
    SLIDESHOW_FILE_ALL,
#endif
#if (MENU_PLAYBACK_SLIDESHOW_FILE_STILL_EN)
    SLIDESHOW_FILE_STILL,
#endif
#if (MENU_PLAYBACK_SLIDESHOW_FILE_MOVIE_EN)
    SLIDESHOW_FILE_MOVIE,
#endif

    SLIDESHOW_FILE_NUM,
}SLIDESHOWFILE_SETTING;

typedef enum{
#if (MENU_PLAYBACK_SLIDESHOW_EFFECT_SIMPLE_EN)
    SLIDESHOW_EFFECT_SIMPLE,
#endif
#if (MENU_PLAYBACK_SLIDESHOW_EFFECT_NOSTALGIC_EN)
    SLIDESHOW_EFFECT_NOSTALGIC,
#endif
#if (MENU_PLAYBACK_SLIDESHOW_EFFECT_STYLISH_EN)
    SLIDESHOW_EFFECT_STYLISH,
#endif
#if (MENU_PLAYBACK_SLIDESHOW_EFFECT_ACTIVE_EN)
    SLIDESHOW_EFFECT_ACTIVE,
#endif

    SLIDESHOW_EFFECT_NUM,
}SLIDESHOWEFFECT_SETTING;

typedef enum{
#if (MENU_PLAYBACK_SLIDESHOW_MUSIC_ON_EN)
    SLIDESHOW_MUSIC_ON,
#endif
#if (MENU_PLAYBACK_SLIDESHOW_MUSIC_OFF_EN)
    SLIDESHOW_MUSIC_OFF,
#endif

    SLIDESHOW_MUSIC_NUM,
}SLIDESHOWMUSIC_SETTING;

typedef enum{
    FILEEDIT_DELETE,
    FILEEDIT_PROTECT,
    FILEEDIT_NUM,
    FILEEDIT_DEFAULT = 0
}FILEEDIT_SETUP;

typedef enum{
    BATTERY_VOLTAGE_EMPTY = 0,
    BATTERY_VOLTAGE_LOW,
    BATTERY_VOLTAGE_LEVEL_0,
    BATTERY_VOLTAGE_LEVEL_1,
    BATTERY_VOLTAGE_LEVEL_2,
    BATTERY_VOLTAGE_FULL,
    BATTERY_VOLTAGE_NUM,
    BATTERY_VOLTAGE_DEFAULT = BATTERY_VOLTAGE_FULL,
    // Special level
    BATTERY_VOLTAGE_CHARGING,
    BATTERY_VOLTAGE_LEVEL_3,    // For WiFi compiler issue

    END_OF_BATTERY_VOLTAGE
}BATTERY_VOLTAGE;

typedef enum{
#if (MENU_MOVIE_SOUND_RECORD_ON_EN)
    MOVIE_SOUND_RECORD_ON,
#endif
#if (MENU_MOVIE_SOUND_RECORD_OFF_EN)
    MOVIE_SOUND_RECORD_OFF,
#endif

    MOVIE_SOUND_RECORD_NUM,
}MOVIE_SOUND_RECORD;

typedef enum{
#if (MENU_MOVIE_POWER_OFF_DELAY_0SEC_EN)
    MOVIE_POWEROFF_TIME_0MIN,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_5SEC_EN)
    MOVIE_POWEROFF_TIME_5SEC,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_10SEC_EN)
    MOVIE_POWEROFF_TIME_10SEC,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_15SEC_EN)
    MOVIE_POWEROFF_TIME_15SEC,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_30SEC_EN)
    MOVIE_POWEROFF_TIME_30SEC,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_1MIN_EN)
    MOVIE_POWEROFF_TIME_1MIN,
    MOVIE_POWEROFF_TIME_60SEC = MOVIE_POWEROFF_TIME_1MIN,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_2MIN_EN)
    MOVIE_POWEROFF_TIME_2MIN,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_3MIN_EN)
    MOVIE_POWEROFF_TIME_3MIN,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_5MIN_EN)
    MOVIE_POWEROFF_TIME_5MIN,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_10MIN_EN)
    MOVIE_POWEROFF_TIME_10MIN,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_15MIN_EN)
    MOVIE_POWEROFF_TIME_15MIN,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_30MIN_EN)
    MOVIE_POWEROFF_TIME_30MIN,
#endif
#if (MENU_MOVIE_POWER_OFF_DELAY_60MIN_EN)
    MOVIE_POWEROFF_TIME_60MIN,
#endif

    MOVIE_POWEROFF_TIME_NUM,
	MOVIE_POWEROFF_TIME_DEFAULT = 0
}MOVIE_POWEROFF_TIME;

typedef enum{
#if (MENU_GENERAL_FLICKER_50HZ_EN)
	FLICKER_50HZ  ,
#endif
#if (MENU_GENERAL_FLICKER_60HZ_EN)
	FLICKER_60HZ  ,
#endif

    FLICKER_NUM,
}FLICKER_HZ;

typedef enum{
    LCD_ROTATE_ON  = 0,
    LCD_ROTATE_OFF  ,
    LCD_ROTATE_NUM ,
    LCD_ROTATE_DEFAULT = 0
}LCD_ROTATE;

typedef enum{
#if (MENU_GENERAL_USB_FUNCTION_MSDC_EN)
    MENU_SETTING_USB_MSDC  ,
#endif
#if (MENU_GENERAL_USB_FUNCTION_PCAM_EN)
    MENU_SETTING_USB_PCAM  ,
#endif

    MENU_SETTING_USB_NUM   ,
}MENU_SETTING_USB_FUNCTION;

typedef enum{
#if (MENU_MOVIE_CLIP_TIME_OFF_EN)
    MOVIE_CLIP_TIME_OFF,
#endif
#if (MENU_MOVIE_CLIP_TIME_1MIN_EN)
    MOVIE_CLIP_TIME_1MIN,
#endif
#if (MENU_MOVIE_CLIP_TIME_2MIN_EN)
    MOVIE_CLIP_TIME_2MIN,
#endif
#if (MENU_MOVIE_CLIP_TIME_3MIN_EN)
    MOVIE_CLIP_TIME_3MIN,
#endif
#if (MENU_MOVIE_CLIP_TIME_5MIN_EN)
    MOVIE_CLIP_TIME_5MIN,
#endif
#if (MENU_MOVIE_CLIP_TIME_10MIN_EN)
    MOVIE_CLIP_TIME_10MIN,
#endif
#if (MENU_MOVIE_CLIP_TIME_30MIN_EN)
    MOVIE_CLIP_TIME_30MIN,
#endif

    MOVIE_CLIP_TIME_NUM,
}MOVIE_CLIPTIME;

typedef enum{
#if (MENU_MOVIE_NIGHT_MODE_ON_EN)
    MOVIE_NIGHT_MODE_ON = 0,
#endif
#if (MENU_MOVIE_NIGHT_MODE_OFF_EN)
    MOVIE_NIGHT_MODE_OFF,
#endif

    MOVIE_NIGHT_MODE_NUM,
    MOVIE_NIGHT_MODE_DEFAULT = MOVIE_NIGHT_MODE_OFF,
}MOVIE_NIGHT_MODE;

typedef enum{
#if (MENU_GENERAL_LCD_POWER_SAVE_OFF_EN)
    LCD_POWER_SAVE_OFF,
#endif
#if (MENU_GENERAL_LCD_POWER_SAVE_10SEC_EN)
    LCD_POWER_SAVE_10SEC,
#endif
#if (MENU_GENERAL_LCD_POWER_SAVE_30SEC_EN)
    LCD_POWER_SAVE_30SEC,
#endif
#if (MENU_GENERAL_LCD_POWER_SAVE_1MIN_EN)
    LCD_POWER_SAVE_1MIN,
#endif
#if (MENU_GENERAL_LCD_POWER_SAVE_3MIN_EN)
    LCD_POWER_SAVE_3MIN,
#endif

    LCD_POWER_SAVE_NUM,
}LCD_PowerSave;

typedef enum{
#if (MENU_GENERAL_GSENSOR_OFF_EN)
    GSENSOR_SENSITIVITY_OFF,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL0_EN)
    GSENSOR_SENSITIVITY_L0,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL1_EN)
    GSENSOR_SENSITIVITY_L1,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL2_EN)
    GSENSOR_SENSITIVITY_L2,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL3_EN)
    GSENSOR_SENSITIVITY_L3,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL4_EN)
    GSENSOR_SENSITIVITY_L4,
#endif

    GSENSOR_SENSITIVITY_NUM,
}GSENSOR_SENSITIVITY;

typedef enum{
#if (MENU_GENERAL_POWERON_GSENSOR_OFF_EN)
    GSENSOR_POWERON_SENSITIVITY_OFF,
#endif
#if (MENU_GENERAL_POWER_ON_GSENSOR_LEVEL0_EN)
    GSENSOR_POWERON_SENSITIVITY_L0,
#endif
#if (MENU_GENERAL_POWER_ON_GSENSOR_LEVEL1_EN)
    GSENSOR_POWERON_SENSITIVITY_L1,
#endif
#if (MENU_GENERAL_POWER_ON_GSENSOR_LEVEL2_EN)
    GSENSOR_POWERON_SENSITIVITY_L2,
#endif

    GSENSOR_POWERON_SENSITIVITY_NUM,
}GSENSOR_POWERON_SENSITIVITY;

typedef enum{
    CHARGER_POWER_OFF_TIME_5SEC,
    CHARGER_POWER_OFF_TIME_15SEC,
    CHARGER_POWER_OFF_TIME_30SEC,
    CHARGER_POWER_OFF_TIME_1MIN,
    CHARGER_POWER_OFF_TIME_NUM,
    CHARGER_POWER_OFF_TIME_DEFAULT = CHARGER_POWER_OFF_TIME_5SEC
}CHARGER_POWER_OFF_TIME;

typedef enum{
    TIMEZONE_GMT_M_12,  //00:0x00
    TIMEZONE_GMT_M_11,
    TIMEZONE_GMT_M_10,
    TIMEZONE_GMT_M_9,
    TIMEZONE_GMT_M_8,
    TIMEZONE_GMT_M_7,   //05:0x05
    TIMEZONE_GMT_M_6,
    TIMEZONE_GMT_M_5,
    TIMEZONE_GMT_M_4,
    TIMEZONE_GMT_M_3_30,
    TIMEZONE_GMT_M_3,   //10:0x0A
    TIMEZONE_GMT_M_2,
    TIMEZONE_GMT_M_1,
    TIMEZONE_GMT,
    TIMEZONE_GMT_P_1,
    TIMEZONE_GMT_P_2,   //15:0x0F
    TIMEZONE_GMT_P_3,
    TIMEZONE_GMT_P_3_30,
    TIMEZONE_GMT_P_4,
    TIMEZONE_GMT_P_4_30,
    TIMEZONE_GMT_P_5,   //20:0x14
    TIMEZONE_GMT_P_5_30,
    TIMEZONE_GMT_P_5_45,
    TIMEZONE_GMT_P_6,
    TIMEZONE_GMT_P_6_30,
    TIMEZONE_GMT_P_7,   //25:0x19
    TIMEZONE_GMT_P_8,
    TIMEZONE_GMT_P_9,
    TIMEZONE_GMT_P_9_30,
    TIMEZONE_GMT_P_10,
    TIMEZONE_GMT_P_11,  //30:0x1E
    TIMEZONE_GMT_NUM,
    TIMEZONE_GMT_OFF,
    TIMEZONE_GMT_DEFAULT = TIMEZONE_GMT_P_8
}TIMEZONE_GMT_LIST;

typedef enum{
#if (MENU_GENERAL_MOTION_DTC_OFF_EN)
    MOTION_DTC_SENSITIVITY_OFF,
#endif
#if (MENU_GENERAL_MOTION_DTC_LOW_EN)
    MOTION_DTC_SENSITIVITY_LOW,
#endif
#if (MENU_GENERAL_MOTION_DTC_MID_EN)
    MOTION_DTC_SENSITIVITY_MID,
#endif
#if (MENU_GENERAL_MOTION_DTC_HIGH_EN)
    MOTION_DTC_SENSITIVITY_HIGH,
#endif

    MOTION_DTC_SENSITIVITY_NUM,
}MOTION_DTC_SENSITIVITY;

typedef enum{
#if (MENU_MOVIE_VMD_REC_TIME_5SEC_EN)
    VMD_REC_TIME_5SEC,
#endif
#if (MENU_MOVIE_VMD_REC_TIME_10SEC_EN)
    VMD_REC_TIME_10SEC,
#endif
#if (MENU_MOVIE_VMD_REC_TIME_30SEC_EN)
    VMD_REC_TIME_30SEC,
#endif
#if (MENU_MOVIE_VMD_REC_TIME_1MIN_EN)
    VMD_REC_TIME_1MIN,
#endif

    VMD_REC_TIME_NUM,
}VMD_REC_TIME;

typedef enum{
    AUTO_REC_ON,
    AUTO_REC_OFF,
    AUTO_REC_NUM,
    AUTO_REC_DEFAULT = AUTO_REC_ON
} AUTO_REC_ENUM;

typedef enum{
#if (MENU_STILL_TIMELAPSE_TIME1_EN)
    TIMELAPSE_INTERVAL_1,
#endif
#if (MENU_STILL_TIMELAPSE_TIME2_EN)
    TIMELAPSE_INTERVAL_2,
#endif
#if (MENU_STILL_TIMELAPSE_TIME3_EN)
    TIMELAPSE_INTERVAL_3,
#endif
#if (MENU_STILL_TIMELAPSE_TIME4_EN)
    TIMELAPSE_INTERVAL_4,
#endif
#if (MENU_STILL_TIMELAPSE_TIME5_EN)
    TIMELAPSE_INTERVAL_5,
#endif
#if (MENU_STILL_TIMELAPSE_TIME6_EN)
    TIMELAPSE_INTERVAL_6,
#endif
#if (MENU_STILL_TIMELAPSE_TIME7_EN)
    TIMELAPSE_INTERVAL_7,
#endif

    TIMELAPSE_INTERVAL_NUM,
	TIMELAPSE_INTERVAL_DEFAULT = 0
}TIMELAPSE_INTERVAL;

typedef enum{
#if (MENU_GENERAL_GPS_STAMP_ON_EN)
    GPS_STAMP_ON,
#endif
#if (MENU_GENERAL_GPS_STAMP_OFF_EN)
    GPS_STAMP_OFF,
#endif

    GPS_STAMP_NUM,
}GPS_STAMP_SETTING;

typedef enum{
    RECODE_GPS_IN_LOG_VIDEO  = 0,
    RECODE_GPS_IN_VIDEO,
    RECODE_GPS_IN_LOG,
    RECODE_GPS_OFF,
    RECODE_GPS_NUM,
    RECODE_GPS_DEFAULT = 0
} RECODE_GPS_SETTING;

typedef enum{
#if (MENU_GENERAL_SPEED_STAMP_ON_EN)
    SPEED_STAMP_ON,
#endif
#if (MENU_GENERAL_SPEED_STAMP_OFF_EN)
    SPEED_STAMP_OFF,
#endif

    SPEED_STAMP_NUM,
}SPEED_STAMP_SETTING;

typedef enum{
#if (MENU_GENERAL_WIFI_ON_EN)
    WIFI_MODE_ON,
#endif
#if (MENU_GENERAL_WIFI_OFF_EN)
    WIFI_MODE_OFF,
#endif

    WIFI_MODE_NUM,
}WIFI_MODE;

typedef enum{
    IMAGE_UPSIDE_DOWN_NORMAL = 0,
    IMAGE_UPSIDE_DOWN_UPSIDE_DOWN,
    IMAGE_UPSIDE_DOWN_MIRROR,
    IMAGE_UPSIDE_DOWN_COLROW,
    IMAGE_UPSIDE_DOWN_NUM
}IMAGE_UPSIDE_DOWN;

//menu setting key maybe in cgi_config.bin
#define COMMON_KEY_STILL_CAP_SIZE			"Camera.Menu.ImageRes"
#define COMMON_KEY_STILL_QUALITY			"Camera.Menu.ImageQuality"
#define COMMON_KEY_BURST_SHOT				"Camera.Menu.BurstShot"
#define COMMON_KEY_MOVIE_SIZE				"Camera.Menu.VideoRes"
#define COMMON_KEY_MOVIE_QUALITY			"Camera.Menu.VideoQuality"
#define COMMON_KEY_MIC_SENSITIVITY			"Camera.Menu.MicSensitivity"
#define COMMON_KEY_PRE_RECD                 "Camera.Menu.VideoPreRecord"
#define COMMON_KEY_VR_CLIP_TIME             "Camera.Menu.LoopingVideo"     //LoopingVideo=VideoClipTime
#define COMMON_KEY_POWER_OFF_DELAY          "Camera.Menu.VideoOffTime"
#define COMMON_KEY_RECD_SOUND               "Camera.Menu.RecordWithAudio"
#define COMMON_KEY_RECD_VOLUME              "Camera.Menu.RecordVolume"
#define COMMON_KEY_VMD_REC_TIME             "Camera.Menu.MotionVideoTime"
#define COMMON_KEY_AUTO_RECORD              "Camera.Menu.AutoRec"
#define COMMON_KEY_TIMELAPSE                "Camera.Menu.Timelapse"
#define COMMON_KEY_SLOWMOTION_EN            "Camera.Menu.SlowMotion"
#define COMMON_KEY_HDR_EN                   "Camera.Menu.HDR"
#define COMMON_KEY_WNR_EN                   "Camera.Menu.WNR"
#define COMMON_KEY_NIGHT_MODE_EN 			"Camera.Menu.NightMode"
#define COMMON_KEY_PARK_TYPE                "Camera.Menu.ParkingMonitor"
#define COMMON_KEY_LDWS_EN                  "Camera.Preview.Adas.LDWS"
#define COMMON_KEY_FCWS_EN                  "Camera.Preview.Adas.FCWS"
#define COMMON_KEY_SAG_EN                   "Camera.Preview.Adas.SAG"
#define COMMON_KEY_CONTRAST                 "Camera.Menu.Contrast"
#define COMMON_KEY_SATURATION               "Camera.Menu.Saturation"
#define COMMON_KEY_SHARPNESS                "Camera.Menu.Sharpness"
#define COMMON_KEY_GAMMA                    "Camera.Menu.Gamma"

#define COMMON_KEY_SCENE					"Camera.Menu.SCENE"
#define COMMON_KEY_EV						"Camera.Menu.EV"
#define COMMON_KEY_ISO						"Camera.Menu.ISO"
#define COMMON_KEY_WB                       "Camera.Menu.AWB"
#define COMMON_KEY_COLOR					"Camera.Menu.color"
#define COMMON_KEY_EFFECT					"Camera.Menu.effect"

#define COMMON_KEY_PB_VOLUME                "Camera.Menu.PlaybackVolume"
#define COMMON_KEY_BEEP                     "Camera.Menu.Beep"
#define COMMON_LCD_BRIGHTNESS               "Camera.Menu.LCDBrightness"
#define COMMON_AUTO_POWER_OFF               "Camera.Menu.AutoPowerOff"
#define COMMON_DATE_TIME_FMT                "Camera.Menu.DateTimeFormat"
#define COMMON_KEY_STICKER_LOGO_TXT         "Camera.Menu.TimeStampLogoTXT"
#define COMMON_KEY_STICKER_GPS				"Camera.Menu.GpsStamp"
#define COMMON_KEY_STICKER_SPEED			"Camera.Menu.SpeedStamp"
#define COMMON_KEY_LANGUAGE                 "Camera.Menu.Language"
#define COMMON_KEY_FLICKER                  "Camera.Menu.Flicker"
#define COMMON_KEY_USB_FUNC                 "Camera.Menu.USB"
#define COMMON_KEY_LCD_POWERS               "Camera.Menu.PowerSaving"
#define COMMON_KEY_GSENSOR_SENS             "Camera.Menu.GSensorSensitivity"
#define COMMON_KEY_GSENSOR_PWR_ON_SENS      "Camera.Menu.GSensorPowerOnSens"
#define COMMON_KEY_TIME_ZONE                "Camera.Menu.TimeZone"
#define COMMON_KEY_MOTION_SENS              "Camera.Menu.MotionSensitivity"
#define COMMON_KEY_WIFI_EN                  "Camera.Menu.WiFi"

#define COMMON_KEY_DRIVER_ID                "Camera.Menu.DriverID"
#define COMMON_KEY_WDR_EN                   "Camera.Menu.WDR"
#define COMMON_KEY_SPEED_CAR                "Camera.Menu.SpeedCar"
#define COMMON_KEY_DISTANCE_UINT            "Camera.Menu.DistanceUnit"
#define COMMON_KEY_SPEED_CAR_CRUISE_SETTING	"Camera.Menu.SpeedCamCruiseSpeedSetting"
#define COMMON_KEY_FATIGUE_ALERT            "Camera.Menu.FatigueAlert"
#define COMMON_KEY_REMIND_HEADLIGHT         "Camera.Menu.RemindHeadlight"
#define COMMON_KEY_BAT_VOLTAGE              "Camera.Menu.BatteryVoltage"
//#define COMMON_KEY_CYCLIC_RECORD            "Camera.Menu.LoopingVideo"

#define COMMON_KEY_PQCONTRAST				"PQContrast"
#define COMMON_KEY_PQBRIGHTNESS				"PQBrightness"
#define COMMON_KEY_PQSATURATION				"PQSaturation"
#define COMMON_KEY_PQCOLORTEMP				"PQColorTemp"

//String Map ID
typedef enum _OSD_STRING_IDS {
IDS_DS_EMPTY = 0,
IDS_DS_MANUAL_SETTINGS,
IDS_DS_SCENE_SELECTION,
IDS_DS_AUTO,
IDS_DS_SCENE_SPORTS,
IDS_DS_SCENE_PORTRAIT,
IDS_DS_SCENE_LANDSCAPE,
IDS_DS_SCENE_TWILIGHTPORTRAIT,
IDS_DS_SCENE_TWILIGHT,
IDS_DS_SCENE_SNOW,
IDS_DS_SCENE_BEACH,
IDS_DS_SCENE_FIREWORKS,
IDS_DS_SCENE_DESCRIPTION,
IDS_DS_FOCUS_WINDOW,
IDS_DS_MULTI,
IDS_DS_CENTER_SPOT,
IDS_DS_FOCUS_WINDOW_DESCRIPTION,
IDS_DS_FOCUS_RANGE,
IDS_DS_NORMAL,
IDS_DS_FOCUS_RANGE_MACRO,
IDS_DS_FOCUS_RANGE_DESCRIPTION,
IDS_DS_METERING,
IDS_DS_METERING_CENTER_WEIGHTED,
IDS_DS_METERING_DESCRIPTION,
IDS_DS_EV,
IDS_DS_EV_P20,
IDS_DS_EV_P17,
IDS_DS_EV_P13,
IDS_DS_EV_P10,
IDS_DS_EV_P07,
IDS_DS_EV_P03,
IDS_DS_EV_0,
IDS_DS_EV_N03,
IDS_DS_EV_N07,
IDS_DS_EV_N10,
IDS_DS_EV_N13,
IDS_DS_EV_N17,
IDS_DS_EV_N20,
IDS_DS_EV_DESCRIPTION,
IDS_DS_ISO,
IDS_DS_ISO_100,
IDS_DS_ISO_200,
IDS_DS_ISO_400,
IDS_DS_ISO_800,
IDS_DS_ISO_1600,
IDS_DS_ISO_3200,
IDS_DS_ISO_DESCRIPTION,
IDS_DS_WB,
IDS_DS_WB_DAYLIGHT,
IDS_DS_WB_CLOUDY,
IDS_DS_WB_FLUORESCENT1,
IDS_DS_WB_FLUORESCENT2,
IDS_DS_WB_FLUORESCENT3,
IDS_DS_WB_INCANDESCENT,
IDS_DS_WB_FLASH,
IDS_DS_WB_ONEPUSH,
IDS_DS_WB_ONE_PUSH_SET,
IDS_DS_WB_DESCRIPTION,
IDS_DS_COLOR,
IDS_DS_COLOR_NATURAL,
IDS_DS_COLOR_VIVID,
IDS_DS_COLOR_PALE,
IDS_DS_COLOR_DESCRIPTION,
IDS_DS_EFFECT,
IDS_DS_EFFECT_SEPIA,
IDS_DS_EFFECT_BLACK_WHITE,
IDS_DS_EFFECT_EMBOSS,
IDS_DS_EFFECT_NEGATIVE,
IDS_DS_EFFECT_SKETCH,
IDS_DS_EFFECT_OIL,
IDS_DS_EFFECT_CRAYON,
IDS_DS_EFFECT_BEAUTY,
IDS_DS_EFFECT_DESCRIPTION,
IDS_DS_FACE_TOUCH,
IDS_DS_FACE_DETECTION,
IDS_DS_TOUCH_SPOT,
IDS_DS_FACE_TOUCH_DESCRIPTION,
IDS_DS_SMILE_DETECTION,
IDS_DS_SMILE_DETECTION_1PERSON,
IDS_DS_SMILE_DETECTION_2PERSONS,
IDS_DS_SMILE_DETECTION_DESCRIPTION,
IDS_DS_SMILE_SENSITIVITY,
IDS_DS_LOW,
IDS_DS_HIGH,
IDS_DS_SMILE_SENSITIVITY_DESCRIPTION,
IDS_DS_MENU,
IDS_DS_QUICK_MENU,
IDS_DS_MOVIE_MODE,
IDS_DS_MOVIE_MODE_SHD,
IDS_DS_MOVIE_MODE_SHD_25P,
IDS_DS_MOVIE_MODE_SHD_24P,
IDS_DS_MOVIE_MODE_FHD_60P,
IDS_DS_MOVIE_MODE_FHD,
IDS_DS_MOVIE_MODE_FHD_HDR,
IDS_DS_MOVIE_MODE_HD,
IDS_DS_MOVIE_MODE_VGA_30P,
IDS_DS_MOVIE_MODE_HD_60P,
IDS_DS_MOVIE_MODE_DESCRIPTION,
IDS_DS_MOVIE_RECORD,
IDS_DS_MOVIE_QUALITY,
IDS_DS_QUALITY_SUPERFINE,
IDS_DS_QUALITY_FINE,
IDS_DS_MOVIE_QUALITY_DESCRIPTION,
IDS_DS_MOVIE_STABLEILIZATION,
IDS_DS_ON,
IDS_DS_OFF,
IDS_DS_MOVIE_STABLE_DESCRIPTION,
IDS_DS_AUTO_SLOW_SHUTTER,
IDS_DS_ASSHUTTER_DESCRIPTION,
IDS_DS_MIC_SENSITIVITY,
IDS_DS_STANDARD,
IDS_DS_MIC_SENSITIVITY_DESCRIPTION,
IDS_DS_STILL_IMAGE_SIZE,
IDS_DS_IMAGE_SIZE_30M,
IDS_DS_IMAGE_SIZE_14M,
IDS_DS_IMAGE_SIZE_12M,
IDS_DS_IMAGE_SIZE_8M,
IDS_DS_IMAGE_SIZE_5M,
IDS_DS_IMAGE_SIZE_3M,
IDS_DS_IMAGE_SIZE_2M,
IDS_DS_IMAGE_SIZE_1_2M,
IDS_DS_IMAGE_SIZE_VGA,
IDS_DS_IMAGE_SIZE_DESCRIPTION,
IDS_DS_FLASH,
IDS_DS_FLASH_SLOW_SYNC,
IDS_DS_FLASH_DESCRIPTION,
IDS_DS_SELFTIMER,
IDS_TIME_1SEC,
IDS_TIME_2SEC,
IDS_TIME_5SEC,
IDS_TIME_10SEC,
IDS_TIME_15SEC,
IDS_TIME_30SEC,
IDS_TIME_60SEC,
IDS_TIME_0MIN,
IDS_TIME_1MIN,
IDS_TIME_2MIN,
IDS_TIME_3MIN,
IDS_TIME_5MIN,
IDS_TIME_10MIN,
IDS_TIME_15MIN,
IDS_TIME_25MIN,
IDS_TIME_30MIN,
IDS_TIME_60MIN,
IDS_DS_SELFTIMER_DESCRIPTION,
IDS_DS_STILL_CAPTURE,
IDS_DS_STILL_QUALITY,
IDS_DS_STILL_QUALITY_DESCRIPTION,
IDS_DS_STILL_STABLEILIZATION,
IDS_DS_STILL_STABLE_DESCRIPTION,
IDS_DS_FLASH_LEVEL,
IDS_DS_FLASH_LEVEL_DESCRIPTION,
IDS_DS_REDEYE_REDUCTION,
IDS_DS_REDEYE_REDUCTION_DESCRIPTION,
IDS_DS_BURST_CAPTURE,
IDS_DS_BURST_SHOT_LO,
IDS_DS_BURST_SHOT_MID,
IDS_DS_BURST_SHOT_HI,
IDS_DS_BURST_CAPTURE_DESCRIPTION,
IDS_DS_DELETE,
IDS_DS_YES,
IDS_DS_NO,
IDS_DS_PROTECT,
IDS_DS_CUT,
IDS_DS_VOLUME,
IDS_DS_VOLUME_DESCRIPTION,
IDS_DS_SLIDE_SHOW,
IDS_DS_ROTATE,
IDS_DS_OK,
IDS_DS_CANCEL,
IDS_DS_RESIZE,
IDS_DS_RESIZE_DESCRIPTION,
IDS_DS_TRIMMING,
IDS_DS_PLAYBACK,
IDS_DS_SLIDE_SHOW_FILES,
IDS_DS_FFILES_ALL,
IDS_DS_FILE_STILL,
IDS_DS_FILE_MOVIE,
IDS_DS_SSHOWFILES_DESCRIPTION,
IDS_DS_SLIDE_SHOW_EFFECTS,
IDS_DS_SIMPLE,
IDS_DS_EFFECTS_NOSTALGIC,
IDS_DS_EFFECTS_STYLISH,
IDS_DS_EFFECTS_ACTIVE,
IDS_DS_SSHOWEFFECTS_DESCRIPTION,
IDS_DS_SLIDE_SHOW_MUSIC,
IDS_DS_SSHOWMUSIC_DESCRIPTION,
IDS_DS_EDIT_TOOL,
IDS_DS_DELETE_ALL_DESCRIPTION,
IDS_DS_DELETE_ALL,
IDS_DS_DELETE_ALL_CONFIRM,
IDS_DS_PROTECT_ALL_DESCRIPTION,
IDS_DS_PROTECT_ALL,
IDS_DS_PROTECT_ALL_CONFIRM,
IDS_DS_MEDIA_TOOL,
IDS_DS_MEDIA_SELECT,
IDS_DS_MEDIA_SD_CARD,
IDS_DS_MEDIA_INTERNAL,
IDS_DS_MEDIA_SELECT_DESCRIPTION,
IDS_DS_FORMAT_SD_CARD,
IDS_DS_FORMAT_CARD_CONFIRM,
IDS_DS_DATA_DELETED,
IDS_DS_FORMAT_INTMEM,
IDS_DS_FORMAT_INTMEM_CONFIRM,
IDS_DS_SD_CARD_INFO,
IDS_DS_CARD_INFO,
IDS_DS_TIME_LEFT,
IDS_DS_PHOTO_LEFT,
IDS_DS_INTMEM_INFO,
IDS_DS_INTMEM_INFORMATION,
IDS_DS_GENERAL_SETTINGS,
IDS_DS_BEEP,
IDS_DS_BEEP_DESCRIPTION,
IDS_DS_LCD_BRIGHTNESS,
IDS_DS_BRIGHT,
IDS_DS_LCD_BRIGHTNESS_DESCRIPTION,
IDS_DS_POWER_OFF,
IDS_DS_POWER_OFF_NEVER,
IDS_DS_POWER_OFF_DESCRIPTION,
IDS_DS_POWER_SAVE,
IDS_DS_POWER_SAVE_DESCRIPTION,
IDS_DS_CLOCK_SETTINGS,
IDS_DS_DATETIME_Y,
IDS_DS_DATETIME_M,
IDS_DS_DATETIME_D,
IDS_DS_DATETIME_FORMAT,
IDS_DS_NONE,
IDS_DS_DATETIME_YMD,
IDS_DS_DATETIME_MDY,
IDS_DS_DATETIME_DMY,
IDS_DS_DATETIME_FORMAT_DESCRIPTION,
IDS_DS_LANGUAGE,
IDS_DS_LANGUAGES_ENGLISH,
IDS_DS_LANGUAGES_SPANISH,
IDS_DS_LANGUAGES_PORTUGUESE,
IDS_DS_LANGUAGES_RUSSIAN,
IDS_DS_LANGUAGES_SCHINESE,
IDS_DS_LANGUAGES_TCHINESE,
IDS_DS_LANGUAGES_GERMAN,
IDS_DS_LANGUAGES_ITALIAN,
IDS_DS_LANGUAGES_LATVIAN,
IDS_DS_LANGUAGES_POLISH,
IDS_DS_LANGUAGES_ROMANIAN,
IDS_DS_LANGUAGES_SLOVAK,
IDS_DS_LANGUAGES_UKRANINIAN,
IDS_DS_LANGUAGES_FRENCH,
IDS_DS_LANGUAGES_KOREAN,
IDS_DS_LANGUAGES_JAPANESE,
IDS_DS_LANGUAGES_CZECH,
IDS_DS_LANGUAGE_DESCRIPTION,
IDS_DS_TV_SYSTEM,
IDS_DS_TV_NTSC,
IDS_DS_TV_PAL,
IDS_DS_TV_SYSTEM_DESCRIPTION,
IDS_DS_HDMI_OUTPUT,
IDS_DS_HDMI_OUTPUT_1080P,
IDS_DS_HDMI_OUTPUT_1080I,
IDS_DS_HDMI_OUTPUT_720P,
IDS_DS_HDMI_OUTPUT_480P,
IDS_DS_HDMI_OUTPUT_DESCRIPTION,
IDS_DS_RESET_SETUP,
IDS_DS_RESET_SETUP_CONFIRM,
IDS_DS_RESET_INFO,
IDS_DS_MSG_CARD_ERROR,
IDS_DS_MSG_STORAGE_FULL,
IDS_DS_MSG_NO_CARD,
IDS_DS_MSG_LOW_BATTERY,
IDS_DS_MSG_FILE_ERROR,
IDS_DS_MSG_CARD_LOCK,
IDS_DS_MSG_CARD_SLOW,
IDS_DS_MSG_USE_RECOMMENDED,
IDS_DS_MSG_ADAPTER_ERROR,
IDS_DS_MSG_INVALID_OPERATION,
IDS_DS_MSG_CANNOT_DELETE,
IDS_DS_MSG_BATTERY_FULL,
IDS_DS_MSG_LENS_ERROR,
IDS_DS_MSG_HDMI_TV,
IDS_DS_MSG_FHD_VR,
IDS_DS_FLASH_LIGHTI,
IDS_DS_LED_LIGHTI,
IDS_DS_DATE_STAMP,
IDS_DS_RECORD,
IDS_DS_STANDBY,
IDS_DS_CAPTUREN,
IDS_DS_PLAYBACK2,
IDS_DS_POWER,
IDS_DS_SHUTTER,
IDS_DS_START,
IDS_DS_STOP,
IDS_DS_ZOOM,
IDS_DS_TELE,
IDS_DS_WIDE,
IDS_DS_UP,
IDS_DS_DOWN,
IDS_DS_LEFT,
IDS_DS_RIGHT,
IDS_DS_SWITCH,
IDS_DS_PAUSE,
IDS_DS_SET,
IDS_DS_PANORAMA,
IDS_DS_FW_VERSION_INFO,
IDS_DS_FW_VERSION,
IDS_DS_FW_TEST,
IDS_DS_FW_BRANCH,
IDS_DS_MOVIE_PRE_RECORD,
IDS_DS_MOVIE_PRE_RECORD_DESCRIPTION,
IDS_DS_EXITMENU,
IDS_DS_DELETE_ONE,
IDS_DS_PROTECT_ONE,
IDS_MOVIE_CLIPTIME,
IDS_MOVIE_POWEROFF_TIME,
IDS_DS_FLICKER,
IDS_FLICKER_50HZ,
IDS_FLICKER_60HZ,
IDS_MOVIE_SOUND_RECORD,
IDS_MOVIE_RECORD_VOLUME,
IDS_DS_MSG_CYCLE_RECORD_ERROR,
IDS_DS_MSG_CYCLE_RECORD_CLEAN_SPACE,
IDS_DS_MSG_SURE_TO_POWER_OFF,
IDS_DS_MSG_SURE_TO_DELETE_SELETED,
IDS_DS_MSG_DELETE_SELETED_ERROR,
IDS_DS_UNPROTECT_ONE,
IDS_DS_UNPROTECT_ALL,
IDS_DS_MSG_SURE_TO_PROTECT_SELETED,
IDS_DS_MSG_SURE_TO_UNPROTECT_SELETED,
IDS_DS_MSG_FORMAT_SD_CARD,
IDS_VIDEO_FILE,
IDS_IMAGE_FILE,
IDS_DS_MSG_FORMAT_SD_CARD_OK,
IDS_DS_MSG_FORMAT_SD_CARD_FAIL,
IDS_DS_MSG_LOCK_CURRENT_FILE,
IDS_MSDC_MODE,
IDS_PCAM_MODE,
IDS_USB_FUNCTION,
IDS_DS_MSG_WAIT_INITIAL_DONE,
IDS_DS_MSG_INSERT_SD_AGAIN,
IDS_DS_LCD_ROTATE,
IDS_DS_LCD_POWER_SAVE,
IDS_DS_MSG_DELETE_FILE_OK,
IDS_DS_MSG_PROTECT_FILE_OK,
IDS_DS_MSG_PLUG_OUT_SD,
IDS_DS_MSG_GOTO_POWER_OFF,
IDS_DS_LED_LIGHT,
IDS_DS_GSENSOR_SENSITIVETY,
IDS_DS_GSENSOR_SENSITIVETY_LEVEL0,
IDS_DS_GSENSOR_SENSITIVETY_LEVEL1,
IDS_DS_GSENSOR_SENSITIVETY_LEVEL2,
IDS_DS_GSENSOR_SENSITIVETY_LEVEL3,
IDS_DS_GSENSOR_SENSITIVETY_LEVEL4,
IDS_DS_MSG_FORMAT_SD_PROCESSING,
IDS_DS_DELAY_POWER_OFF,
IDS_DSC_MODE,
IDS_DV_MODE,
IDS_DS_MODE,
IDS_DS_MODE_TAKE_PHOTO,
IDS_DS_MODE_BROWSER_PHOTO,
IDS_DS_MODE_BROWSER_VIDEO,
IDS_DS_MODE_PLAYBACK_PHOTO,
IDS_DS_MODE_PLAYBACK_VIDEO,
IDS_DS_GPS_INFO_STATUS,
IDS_DS_TIME_ZONE,
IDS_DS_TIME_ZONE_GMT_M_12,
IDS_DS_TIME_ZONE_GMT_M_11,
IDS_DS_TIME_ZONE_GMT_M_10,
IDS_DS_TIME_ZONE_GMT_M_9,
IDS_DS_TIME_ZONE_GMT_M_8,
IDS_DS_TIME_ZONE_GMT_M_7,
IDS_DS_TIME_ZONE_GMT_M_6,
IDS_DS_TIME_ZONE_GMT_M_5,
IDS_DS_TIME_ZONE_GMT_M_4,
IDS_DS_TIME_ZONE_GMT_M_3_30,
IDS_DS_TIME_ZONE_GMT_M_3,
IDS_DS_TIME_ZONE_GMT_M_2,
IDS_DS_TIME_ZONE_GMT_M_1,
IDS_DS_TIME_ZONE_GMT,
IDS_DS_TIME_ZONE_GMT_P_1,
IDS_DS_TIME_ZONE_GMT_P_2,
IDS_DS_TIME_ZONE_GMT_P_3,
IDS_DS_TIME_ZONE_GMT_P_3_30,
IDS_DS_TIME_ZONE_GMT_P_4,
IDS_DS_TIME_ZONE_GMT_P_4_30,
IDS_DS_TIME_ZONE_GMT_P_5,
IDS_DS_TIME_ZONE_GMT_P_5_30,
IDS_DS_TIME_ZONE_GMT_P_5_45,
IDS_DS_TIME_ZONE_GMT_P_6,
IDS_DS_TIME_ZONE_GMT_P_6_30,
IDS_DS_TIME_ZONE_GMT_P_7,
IDS_DS_TIME_ZONE_GMT_P_8,
IDS_DS_TIME_ZONE_GMT_P_9,
IDS_DS_TIME_ZONE_GMT_P_9_30,
IDS_DS_TIME_ZONE_GMT_P_10,
IDS_DS_TIME_ZONE_GMT_P_11,
IDS_DS_TIME_ZONE_GMT_P_12,
IDS_DS_TIME_ZONE_GMT_P_13,
IDS_DS_MSG_UNLOCK_FILE,
IDS_DS_MSG_NO_FILE,
IDS_DS_MSG_CAPTURE_SCREEN,
IDS_DS_STAMP_DATELOGO,
IDS_DS_STAMP_DATE,
IDS_DS_STAMP_LOGO,
IDS_DS_STAMP,
IDS_DS_STAMP_DESCRIPTION,
IDS_DS_MIDDLE,
IDS_DS_DATETIME_H,
IDS_DS_DATETIME_MM,
IDS_DS_MOTION_DETECTION,
IDS_DS_MOTION_DETECTION_DESCRIPTION,
IDS_DS_SELECT,
IDS_VMD_REC_TIME,
IDS_VMD_SHOT_NUM,
IDS_DS_MSG_VMD,
IDS_DS_P,
IDS_DS_DATETIME_S,
IDS_AUTO_REC,
IDS_DS_LAST,
IDS_DS_ALL,
IDS_DS_SEC,
IDS_DS_TIMELAPSE,
IDS_DS_BOOTUP_MODE,
IDS_DS_RECORD_EX,
IDS_DSC_MODE_EX,
IDS_DS_BURST_CAPTURE_EX,
IDS_DS_TIMELAPSE_EX,
IDS_DS_MOVIE_MODE_FHD_EX,
IDS_DS_MOVIE_MODE_HD_EX,
IDS_DS_MOVIE_MODE_HD_60P_EX,
IDS_DS_MOVIE_MODE_VGA_30P_EX,
IDS_DS_POWER_OFF_1MIN_EX,
IDS_DS_POWER_OFF_5MIN_EX,
IDS_DS_GSENSOR_SENSITIVETY_DESCRIPTION,
IDS_DS_SELECT_A_FILE,
IDS_DS_NIGHT_MODE,
IDS_DS_NIGHT_MODE_DESCRIPTION,
IDS_DS_SWITCH_LCD_AV,
IDS_DS_MODE_BROWSER_EVENT,
IDS_DS_DRIVER_ID_SETTINGS,
IDS_DS_DRIVER_ID_D0,
IDS_DS_DRIVER_ID_D1,
IDS_DS_DRIVER_ID_D2,
IDS_DS_DRIVER_ID_D3,
IDS_DS_DRIVER_ID_D4,
IDS_DS_DRIVER_ID_D5,
IDS_DS_DRIVER_ID_D6,
IDS_DS_DRIVER_ID_D7,
IDS_DS_DRIVER_ID_D8,
IDS_DS_POWERON_GSENSOR_SENSITIVETY,
IDS_DS_WIFI,
IDS_DS_GENERAL_SETTINGS_DESCRIPTION,
IDS_DS_WIFI_MODE,
IDS_DS_WIFI_MODE_AP,
IDS_DS_WIFI_MODE_STATION,
IDS_DS_WIFI_AP_SSID,
IDS_DS_WIFI_AP_PASSWORD,
IDS_DS_WIFI_STATION1_SSID,
IDS_DS_WIFI_STATION1_PASSWORD,
IDS_DS_WIFI_STATION2_SSID,
IDS_DS_WIFI_STATION2_PASSWORD,
IDS_DS_WIFI_STATION3_SSID,
IDS_DS_WIFI_STATION3_PASSWORD,
IDS_DS_WIFI_STATION4_SSID,
IDS_DS_WIFI_STATION4_PASSWORD,
IDS_DS_WIFI_STATION5_SSID,
IDS_DS_WIFI_STATION5_PASSWORD,
IDS_DS_WIFI_STATION6_SSID,
IDS_DS_WIFI_STATION6_PASSWORD,
IDS_DS_VIDEO_TYPE,
IDS_DS_VIDEO_TYPE_NORMAL,
IDS_DS_VIDEO_TYPE_PARKING,
IDS_DS_VIDEO_TYPE_EMERGENCY,
IDS_DS_FW_READING,
IDS_DS_FW_UPDATING,
IDS_DS_LDWS_CALI,
IDS_DS_LDWS,
IDS_DS_FCWS,
IDS_DS_SAG,
IDS_DS_HDR,
IDS_DS_MSG_OPENFILE_WAIT,
IDS_DS_MOVIE_MODE_FHD_24P,
IDS_DS_MOVIE_MODE_HD_24P,
IDS_DS_CONTRAST,
IDS_DS_CONTRAST_DESCRIPTION,
IDS_DS_SATURATION,
IDS_DS_SATURATION_DESCRIPTION,
IDS_DS_SHARPNESS,
IDS_DS_SHARPNESS_DESCRIPTION,
IDS_DS_GAMMA,
IDS_DS_GAMMA_DESCRIPTION,
IDS_DS_SLOWMOTION,
IDS_DS_SLOWMOTION_X1,
IDS_DS_SLOWMOTION_X2,
IDS_DS_SLOWMOTION_X4,
IDS_DS_SLOWMOTION_X8,
IDS_DS_VIDEO_TIMELAPSE,
IDS_DS_WNR,
IDS_DS_REARCAMTYPE,
IDS_DS_REARCAM_NONE,
IDS_DS_AIT,
IDS_DS_SONIXMJPEG2H264,
IDS_DS_SONIXMJPEG,
IDS_DS_TVDECODER,
IDS_DS_BAYERSENSOR,
IDS_DS_YUVSENSOR,
IDS_DS_COLORTEMP,
IDS_DS_COLORTEMP_DEF,
IDS_DS_COLORTEMP_WARMCOLOR,
IDS_DS_COLORTEMP_COOLCOLOR,
IDS_DS_MODE1,
IDS_DS_MODE2,
IDS_DS_MODE3,
IDS_DS_MODE4,
IDS_DS_MODE5,
IDS_DS_INC,
IDS_DS_DEC,
IDS_DS_SYS_SETTINGS,
IDS_DS_VIDEO_CAM_ID,
IDS_DS_VIDEO_CAM_1ST,
IDS_DS_VIDEO_CAM_2ND,
IDS_DS_VIDEO_CAM_3RD,
IDS_DS_VIDEO_CAM_4TH,
IDS_DS_SYSTEM_POWER_OFF,
IDS_DS_MOVIE_MODE_4K_25,
IDS_DS_MOVIE_MODE_1440_30,
IDS_DS_END
} OSD_STRING_IDS;

extern const char* osdstringpool[];
#define MAP_STRINGID(x) osdstringpool[x]

typedef enum _WMSG_INFO {
    WMSG_NONE = 0           ,
    WMSG_CARD_ERROR         ,
    WMSG_STORAGE_FULL       ,
    WMSG_NO_CARD            ,
    WMSG_LOW_BATTERY        ,
    WMSG_FILE_ERROR         ,
    WMSG_CARD_LOCK          ,
    WMSG_CARD_SLOW          ,
    WMSG_ADAPTER_ERROR      ,
    WMSG_INVALID_OPERATION  ,
    WMSG_CANNOT_DELETE      ,
    WMSG_BATTERY_FULL       ,
    WMSG_LENS_ERROR         ,
    WMSG_HDMI_TV            ,
    WMSG_FHD_VR             ,
    WMSG_PLUG_OUT_SD_CARD   ,
    WMSG_WAIT_INITIAL_DONE  ,
    WMSG_INSERT_SD_AGAIN    ,
    WMSG_FORMAT_SD_PROCESSING,
    WMSG_FORMAT_SD_CARD_OK  ,
    WMSG_FORMAT_SD_CARD_FAIL,
    WMSG_COME2EMER          ,
    WMSG_TIME_ERROR         ,
    WMSG_SHOW_FW_VERSION    ,
    WMSG_START_RECORD       ,
    WMSG_START_NORMAL_RECORD,
    WMSG_SPEEDCAM_ADDED     ,
    WMSG_ADD_SPEEDCAM       ,
    WMSG_DEL_SPEEDCAM       ,
    WMSG_NO_POI_SPACE       ,
    WMSG_WAIT_GPS_FIX       ,
    WMSG_PARKING_MODE_DISABLE,
    WMSG_LDWS_RightShift    ,
    WMSG_LDWS_LeftShift     ,
    WMSG_SEAMLESS_ERROR     ,
    WMSG_FORMAT_SD_CARD     ,
    WMSG_LOCK_CURRENT_FILE  ,
    WMSG_UNLOCK_CUR_FILE    ,
    WMSG_DELETE_FILE_OK     ,
    WMSG_PROTECT_FILE_OK    ,
    WMSG_GOTO_POWER_OFF     ,
    WMSG_NO_FILE_IN_BROWSER ,
    WMSG_CAPTURE_CUR_FRAME  ,
    WMSG_FCWS               ,
    WMSG_FATIGUEALERT       ,
    WMSG_OPENFILE_WAIT      ,
    WMSG_NO_CARD1           ,
    WMSG_NO_CARD2           ,
    WMSG_CARD2_FULL         ,
    WMSG_NO_CARD2_2         ,
    WMSG_BACKUP_FINISH      ,
    WMSG_MOTION_OPERATING_DESCRIPTION,
    WMSG_MSG_EMERGENCY_FILE_FULL,
    WMSG_REMIND_HEADLIGHT,
    WMSG_PARKING_OPERATING_DESCRIPTION,
    WMSG_SYSTEM_POWER_OFF,
    END_OF_WMSG
} WMSG_INFO;
/*===========================================================================
 * Extern variable
 *===========================================================================*/
extern SMENUSTRUCT  sMainMenuVideo;
extern SMENUSTRUCT 	sMainMenuStill;
extern SMENUSTRUCT  sMainMenuManual;
extern SMENUSTRUCT  sMainMenuPlayback;
extern SMENUSTRUCT  sMainMenuEdit;
extern SMENUSTRUCT  sMainMenuMedia;
extern SMENUSTRUCT  sMainMenuGeneral;
/*===========================================================================
 * Macro define
 *===========================================================================*/
#define MENU_PAGE_NUM   sizeof(MenuPageList)/sizeof(PSMENUSTRUCT)
/* For RTC Default Time */
#ifndef RTC_DEFAULT_YEAR
#define RTC_DEFAULT_YEAR                (2019)
#endif
#ifndef RTC_DEFAULT_MONTH
#define RTC_DEFAULT_MONTH               (1)
#endif
#ifndef RTC_DEFAULT_DAY
#define RTC_DEFAULT_DAY                 (1)
#endif

#ifndef RTC_DEFAULT_HOUR 
#define RTC_DEFAULT_HOUR                (8)
#endif
#ifndef RTC_DEFAULT_MIN
#define RTC_DEFAULT_MIN                 (0)
#endif
#ifndef RTC_DEFAULT_SEC
#define RTC_DEFAULT_SEC                 (0)
#endif

#ifndef RTC_MAX_YEAR
#define RTC_MAX_YEAR                    (2099)
#endif
#ifndef RTC_MIN_YEAR
#define RTC_MIN_YEAR                    (RTC_DEFAULT_YEAR)
#endif
#define RTC_MAX_MONTH                   (12)
#define RTC_MIN_MONTH                   (1)
#define RTC_MAX_DAY_31                  (31)
#define RTC_MAX_DAY_30                  (30)
#define RTC_MAX_DAY_FEB_LEAP_YEAR       (29)
#define RTC_MAX_DAY_FEB_NONLEAP_YEAR    (28)
#define RTC_MIN_DAY                     (1)
#define RTC_MAX_HOUR                    (23)
#define RTC_MIN_HOUR                    (0)
#define RTC_MAX_MIN                     (59)
#define RTC_MIN_MIN                     (0)
#define RTC_MAX_SEC                     (59)
#define RTC_MIN_SEC                     (0)

/* For Clock Setting : YYYY/MM/DD HH/MM/SS */
#define IDX_YEAR                        (0)
#define IDX_MONTH                       (1)
#define IDX_DAY                         (2)
#define IDX_HOUR                        (3)
#define IDX_MIN                         (4)
#define IDX_SEC                         (5)
#define CHECK_PASS                      (0xFF)

#define CHECK_YEAR                      (0x01)
#define CHECK_MONTH                     (0x02)
#define CHECK_DAY                       (0x04)
#define CHECK_HOUR                      (0x08)
#define CHECK_MIN                       (0x10)
#define CHECK_SEC                       (0x20)
#define CHECK_ALL                       (CHECK_YEAR | CHECK_MONTH | CHECK_DAY | CHECK_HOUR | CHECK_MIN | CHECK_SEC)

#ifdef DUAL_OS
const char MenuCfgFile[] = "/misc/cgi_config.bin";
#else
const char MenuCfgFile[] = "/customer/wifi/cgi_config.bin";
#endif
#define GET_CONFIG_SETTING   "nvconf get 0 "
#define SET_CONFIG_SETTING   "nvconf set 0 "
/*===========================================================================
 * Function prototype 
 *===========================================================================*/
bool MenuSetting_GetCB(char *cmenu_string, ...);
int ParseMenuSet(const char *file, MenuInfo* pmi /*out*/);
void Menu_WriteSetting(void);
pMenuInfo MenuSettingConfig(void);
bool Menu_General_EnGet(char *key, char *value, int len);
bool Menu_General_EnSet(const char *key, char *value);
void MenuSettingInit(void);
void ListAllMenuSetting(MenuInfo *Info);
#endif //_MENU_COMMON_H_

